### PR TITLE
Update BinarySearch.java

### PR DESCRIPTION
**Pull request by sunilnitdgp**
Added iterative binary search

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [ ] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by sunilnitdgp** [comment]
@siriak Please review this one as well.

**Review by siriak — COMMENTED** [review]
I think it's already implemented here https://github.com/TheAlgorithms/Java/blob/152e29034d248226395ee659ce6deb2cbbc62805/src/main/java/com/thealgorithms/searches/PerfectBinarySearch.java#L3. But you can update the implementation there and add JUnit tests

**Comment by sunilnitdgp** [comment]
@siriak updated PerfectBinarySearch's implementation and added test cases as well.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
