### PR TITLE
solved problem of lowercase letters

### PR DESCRIPTION
**Pull request by aniket3991**
solved problem with lowercase letters

### CODE REVIEW

**Comment by drabbit75** [comment]
it seems not to solve lowercase letter problem . do you want to solve "n=0" bug ?

**Comment by drabbit75** [comment]
ready to close with the doubt

**Comment by aniket3991** [comment]
@drabbit75  can you give me an input where you find problems in lower case letters

**Comment by drabbit75** [comment]
> @drabbit75 can you give me an input where you find problems in lower case letters

the codes seems not to solve "lower case problem", what  bugs do you want to fix

**Comment by aniket3991** [comment]
actually when you wanted to covert a more than base 10 numbers, you have to give the values of "abcdef" in capital letters otherwise code was not working so i fixed that

**Comment by drabbit75** [comment]
in the codes ：
 {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
                'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V',
                'W', 'X', 'Y', 'Z'};" // digitsForBase contains all the valid digits for the base given".
this limits the input and I think it is not a bug and not neccesary to fix personally.

**Comment by aniket3991** [comment]
So you can say that i expanded the input limit

**Review by mamadaliev — APPROVED** [review]

**Pull request closed without merging**
