### PR TITLE
Tarjans algo

### PR DESCRIPTION
**Pull request by shivu2002a**
- [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ x] This pull request is all my own work -- I have not plagiarized it.
- [ x] All filenames are in PascalCase.
- [ x] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by shivu2002a** [comment]
@siriak I've added the Tarjan's algo along with test cases

**Comment by shivu2002a** [comment]
@siriak How can I be a member of this organization? I'm interested.

**Review by siriak — APPROVED** [review]
Looks good, thanks! As for the membership, this can be discussed in our Discord server

**Comment by shivu2002a** [comment]
> Looks good, thanks! As for the membership, this can be discussed in our Discord server

Sure.

**Pull request merged**
