### PR TITLE
Add Bucket Sort Algorithm

### LINKED ISSUE #96: Add more algorithms
This repo has less contributions. Please add more algorithms. 

See the structure and README of this repo for reference
https://github.com/TheAlgorithms/Python

### PR DESCRIPTION
**Pull request by YJDave**
Fixes #96

### CODE REVIEW

**Comment by YJDave** [comment]
@AnupKumarPanwar please review PR!! and let me know suggestions!

**Comment by YJDave** [comment]
@varunu28 I understand your first point. But didn't get second point. Do you want me to convert it into generic in terms of data type or in terms of range of input?

**Comment by varunu28** [comment]
@YJDave Your algorithm should sort the arrays of all data types. Be it string array or an integer array. Please check [Insertion Sort](https://github.com/TheAlgorithms/Java/blob/master/Sorts/InsertionSort.java) for reference

**Comment by YJDave** [comment]
Okay!!
Will update soon.

**Pull request closed without merging**
