### PR TITLE
add permutation

### PR DESCRIPTION
**Pull request by cpiao3**
### **Describe your change:**

- [ x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ x] This pull request is all my own work -- I have not plagiarized.
- [ x] I know that pull requests will not be merged if they fail the automated tests.
- [ x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ x] All new Java files are placed inside an existing directory.
- [ x] All filenames are in all uppercase characters with no spaces or dashes.
- [ x] All functions and variable names follow Java naming conventions.
- [ x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cpiao3** [comment]
@siriak can you review this; added combination as well.

**Review by siriak — CHANGES_REQUESTED** [review]
The code looks good, please also remove main() and add tests as in https://github.com/TheAlgorithms/Java/blob/ab9f74c2ee0dee9174616f2154f1161d600f68cd/src/test/java/com/thealgorithms/maths/KaprekarNumbersTest.java

**Comment by cpiao3** [comment]
@siriak added tests and deleted main()

**Review by siriak — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
