### PR TITLE
CountSetBits algorithm added

### PR DESCRIPTION
**Pull request by Pankaj-Bind**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
[https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/others/countSetBits.java](url)
Duplicate

**Comment by Pankaj-Bind** [comment]
But I haven't seen anyone similar to this.

**Comment by vil02** [comment]
As pointed out by @BamaCharanChhandogi [`countSetBits`](https://github.com/TheAlgorithms/Java/blob/47a9b1b647d890d3cce50cd21774f5c78c350782/src/main/java/com/thealgorithms/others/countSetBits.java) already exists. But it needs some _cleanup_:
- the method [countsetBits](https://github.com/TheAlgorithms/Java/blob/47a9b1b647d890d3cce50cd21774f5c78c350782/src/main/java/com/thealgorithms/others/countSetBits.java#L43) could be marked as `static` and the whole class could be a _proper utility_,
- tests should include negative inputs,
- the class should be renamed to `CountSetBits` and possibly moved to [`src/main/java/com/thealgorithms/bitmanipulation`](https://github.com/TheAlgorithms/Java/tree/master/src/main/java/com/thealgorithms/bitmanipulation),
- [`BrianKernighanAlgorithm`](https://github.com/TheAlgorithms/Java/blob/47a9b1b647d890d3cce50cd21774f5c78c350782/src/main/java/com/thealgorithms/others/BrianKernighanAlgorithm.java) provides the same functionality and it should be removed.

@Pankaj-Bind would you like to open a new PR with changes decried above?

**Comment by Pankaj-Bind** [comment]
yes

**Pull request closed without merging**
