### PR TITLE
Request to add Trapping Rain Water in misc.

### PR DESCRIPTION
**Pull request by AnuragKumar007**
It's my 1st PR. I want to add Classic question "**Trapping Rainwater**" in misc folder. I've tried my best to keep the code neat & clean. Also used comments to make the code easy to understand for all.
Request to add a **Classic Question**.
### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by gkgaurav31** [comment]
In line 39, 

`trappedWater += waterLevel - height[i]; //width =1`

It will have negative value (which is not possible for water trapped) if height[i] is more than both leftMax[i] and rightMax[i].

We can fix that in the following way:

```
//If the currentHeight is more than the max on left and right both, take 0.
trappedWater += Math.max(0, Math.min(leftMax[i],rightMax[i])-height[i]);
```

**Comment by AnuragKumar007** [comment]
> 

Thanks! but can you tell me the test case too? 
I think the code is correct. Let's take an array - {3,0,5,2,0,2} 
it should give output - 5 and it's giving

**Comment by gkgaurav31** [comment]
Just noticed, the way you've generated the prefix/suffix array takes care of this edge case. Should be okay.

**Review by siriak — CHANGES_REQUESTED** [review]
The code looks good, could you please add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

**Pull request closed without merging**
