### PR TITLE
check any number is odd or even

### PR DESCRIPTION
**Pull request by rashed-08**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by siriak** [comment]
Please check why linter fails
image

**Comment by debasishbsws** [comment]
the class name `BitManipulation` is a little odd. Can you name it a little differently?

**Comment by rashed-08** [comment]
Sorry, I also push the code. The issue is closed with another PR.

**Comment by debasishbsws** [comment]
This is not required anymore. You can try something else.

**Pull request closed without merging**
