### PR TITLE
Add Euler method

### PR DESCRIPTION
**Pull request by algobytewise**
### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by ayaankhan98 — COMMENTED** [review]
Thanks for your contribution, please update the documentation according to Java docs standard.

refer to the documentation of this [file](https://github.com/TheAlgorithms/Java/blob/master/Misc/ColorContrastRatio.java) in case you need any help regarding documentation.

also add tests

**Comment by algobytewise** [comment]
Thanks for the feedback. I've reformatted the documentation and I've implemented tests to validate that the numerical arguments are in range.

**Comment by danielUTM** [comment]
I just created another pull request that kept failing on the "Prettier / prettier" check with the same error message you are getting. I fixed the issue by changing branch I was comitting from to be called master and it fixed it, hope this helps you.

**Comment by algobytewise** [comment]
Thank you for this insight! I've tried it and it also solved the problem for me, see #2148 . I'll close this pull request & open an issue.

**Pull request closed without merging**
