### PR TITLE
Create Problem12.java

### PR DESCRIPTION
**Pull request by deadshotsb**
Added solution for problem 12 of Project Euler

### **Describe your change:**

Added solution for problem 12 of Project Euler

* [X] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**

* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Java files are placed inside an existing directory.
* [ ] All filenames are in all uppercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Java naming conventions.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by yansheng836 — COMMENTED** [review]
I found some format problem, may be you should see [pull_request_template](https://github.com/TheAlgorithms/Java/blob/master/.github/pull_request_template.md) again.

**Comment by deadshotsb** [comment]
@yansheng836 Thanks for reviewing my work, can you be more specific about the format problems, are you referring to the checklists in my PR or any particular code segment in my PR?

**Comment by shellhub** [comment]
Can you rename class name `Problem_12_Highly_Divisible_Triangular_Number` to `Problem12` ? . follow this file: https://github.com/TheAlgorithms/Java/blob/master/ProjectEuler/Problem01.java

**Comment by deadshotsb** [comment]
@shellhub you can have a look now.

**Review by shellhub — APPROVED** [review]

**Comment by shellhub** [comment]
> @shellhub you can have a look now.

I reformated code. Hope you don't mind.

**Comment by deadshotsb** [comment]
> > @shellhub you can have a look now.
> 
> I reformated code. Hope you don't mind.

@shellhub completely fine by me, it is important to upgrade the standards of our PR if required.

**Pull request merged**
