### PR TITLE
Added new File WordBoggle.java in Java/Misc

### PR DESCRIPTION
**Pull request by AzadN**
@shellhub this is my 2nd pull request out of the original pull request #1990 with multiple files. Please review it and merge if found useful.

Edit: I actually wanted to issue a separate 3rd pull request for RangeInSortedArray.java but it was added as a change to this PR itself I don't know why so please go through that file also.
I tried merging PR from a different branch on my fork to master of this repo but it didn't pass all the checks hence reverted back to adding changes from my own fork's master to origin's master.

@Kush1101 could you too review this?

### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by AkMo3** [comment]
I Don't know buddy what issue it is throwing to you. I have sent a PR containing exactly your files, and no issues with that PR.

**Comment by AzadN** [comment]
> I Don't know buddy what issue it is throwing to you. I have sent a PR containing exactly your files, and no issues with that PR.

All my checks have passed successfully currently. You can check here itself. Thanks anyways for issuing the PR again for my help :)

**Comment by AkMo3** [comment]
> 
> 
> > I Don't know buddy what issue it is throwing to you. I have sent a PR containing exactly your files, and no issues with that PR.
> 
> All my checks have passed successfully currently. You can check here itself. Thanks anyways for issuing the PR again for my help :)

Congratulations, finally every thing fine. Hope it gets mergerd as soon as possible.

**Comment by AzadN** [comment]
@shellhub to issue separate PRs for each of the 8 remaining files, I'd have to issue separate PRs by creating separate branches on my local fork of the original Java repository and then issue PRs per branch. But on doing so, the **prettier** check fails since it won't be able to locate the branches with the same name on the original repository. So every time that one check will surely fail. Would it be an issue? Please do review my current separate PRs and help me with this doubt :)

**Comment by AkMo3** [comment]
It is not necessary that you send PR only through the development or master branch. You can create unique branches for every PR. And a fun fact, usually PR is sent through a branch which gives direct idea about what is this PR about. You can also send through the master branch but unless the earlier PR is closed, the PR will be merged with previous one.  

Also pardon me but I am not familiar with trees. I am just a first year undergrad who hasn't joined the college yet. I would really try to review other than those, just I am a bit busy now days so hardly left with an hour or two, so it is hard for me to review. But I would surely try.

**Pull request merged**
