### PR TITLE
Added the retrieval of minimum and maximum element from stack at O(1)

### PR DESCRIPTION
**Pull request by S-M-J-I**
- [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [X] This pull request is all my own work -- I have not plagiarized it.
- [X] All filenames are in PascalCase.
- [X] All functions and variable names follow Java naming conventions.
- [X] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [X] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by saahil-mahato** [comment]
This is missing test case when the `maxStack` is empty and we attempt to `push` or `pop`. Please confirm. Thanks.

**Comment by S-M-J-I** [comment]
> This is missing test case when the `maxStack` is empty and we attempt to `push` or `pop`. Please confirm. Thanks.

Hi. Thanks for the comment. The test case when `maxStack` is empty and we attempt to `pop` from it is present as `testNullMax()`. As for the `push`, the `maxStack` will not be empty as long as the `mainStack` has at least one value. Thank you for bringing this to my attention, I will add a test case where we clear the stack and then try to push into it and try to retrive the max value.

**Review by siriak — COMMENTED** [review]
We do not add leetcode problems, please add references to other sources if they exist

**Comment by S-M-J-I** [comment]
> We do not add leetcode problems, please add references to other sources if they exist

Hello @siriak, I added another ref for this algorithm.

**Comment by S-M-J-I** [comment]
Hello @siriak, I have made the reference changes as advised. Please let me know your reviews.

**Pull request merged**
