### PR TITLE
Implemented Fast Inverse Sqrt Method

### PR DESCRIPTION
**Pull request by DougDevelopz**
### **Describe your change:**

- [x ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x ] This pull request is all my own work -- I have not plagiarized.
- [x ] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ x] All new Java files are placed inside an existing directory.
- [x ] All filenames are in all uppercase characters with no spaces or dashes.
- [ x] All functions and variable names follow Java naming conventions.
- [ x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
The code looks good, could you add some automated tests as well?

**Comment by DougDevelopz** [comment]
> The code looks good, could you add some automated tests as well?

I have just pushed my latest commit that consists of automated tests between both methods

**Comment by siriak** [comment]
Take a look at the files here https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms, `main` is an entry point and won't be run by a testing framework. It would help if you had JUnit tests https://www.vogella.com/tutorials/JUnit/article.html

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Comment by siddhant2002** [comment]
@siriak Please check the pr

**Comment by siriak** [comment]
@siddhant2002 which PR?

**Pull request closed without merging**
