### PR TITLE
Add least common multiple algorithm 

### PR DESCRIPTION
**Pull request by LauKinHoong**
### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References
#3213 

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains Fixes: #{$ISSUE_NO}.

### CODE REVIEW

**Comment by LauKinHoong** [comment]
@siriak may I know am I doing something wrong which prevent me for merging? Thank you :)

**Review by siriak — CHANGES_REQUESTED** [review]
Thanks for contributing, please, check that only your changes are included in the PR. It seems that merge conflicts were resolved incorrectly

**Comment by LauKinHoong** [comment]
> Thanks for contributing, please, check that only your changes are included in the PR. It seems that merge conflicts were resolved incorrectly

May I request your guide on what should I do now ?

**Comment by LauKinHoong** [comment]
How about now? Does it resolve the merge conflicts? It should be included only my changes in the PR now.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
