### PR TITLE
refactor: cleanup `CycleSort`

### PR DESCRIPTION
**Pull request by alxkm**
Cleanup CycleSort. Adding test for it. Simplify code.

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
Looking good but here add more test cases

**Comment by alxkm** [comment]
> Looking good but here add more test cases

Thank you. I've been eager to enhance test coverage for sorting algorithms for quite some time.

**Comment by alxkm** [comment]
Hello, @BamaCharanChhandogi everything fixed now

**Review by BamaCharanChhandogi — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
