### PR TITLE
2212

### PR DESCRIPTION
**Pull request by anishsaraogi**
Issue #2212 fixed and Password Validator added.

### CODE REVIEW

**Comment by esparev** [comment]
Technically, it's not wrong, and the code wasn't broken, but it isn't working the way it's supposed to with the changes you made.

**Comment by esparev** [comment]
I suggest you look again at the code that I have and I strongly recommend that you give the variables a more explicit and explanatory name.

**Comment by anishsaraogi** [comment]
It's probably the special characters because as I saw, your code includes more special characters than I put. I will add it asap.

**Comment by esparev** [comment]
Appreciate the attention, thank you @anishsaraogi

**Pull request closed without merging**
