### PR TITLE
Added script in JAVA for how many times an array has been rotated in O(log N) 

### PR DESCRIPTION
**Pull request by nirmalya8**
Added the script in Searches Folder
### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [ ] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
Please add tests showing how it works. It seems that it won't work for arrays with duplicate elements

**Comment by nirmalya8** [comment]
> Please add tests showing how it works. It seems that it won't work for arrays with duplicate elements

Can you tell me where to add the tests. I added 3 testcases in the file as comments. 
As for duplicate elements, I am checking the script and will update the PR

**Comment by nirmalya8** [comment]
Hey @siriak , I couldn't find a solution for duplicate elements. If there are duplicate elements then maybe the complexity has to go up. Can you tell me where to add the tests(I don't know about them, can you explain)?

And, I found out, I can add the solution to another such question:
 Given a rotated sorted array(rotated from its initial sorted position.), search for an element. 
    Input-Output:
    Eg. [11,12,15,18,2,5,6,8]
    Search Element: 6
    Position: 6
Again, in O(log n) time.

**Comment by siriak** [comment]
Just mention in the description that the array cannot contain duplicates. As for tests, we don't have anything set up, so your comments will serve the purpose.

**Comment by nirmalya8** [comment]
> Just mention in the description that the array cannot contain duplicates. As for tests, we don't have anything set up, so your comments will serve the purpose.

Done it. Thanks!

**Review by siriak — APPROVED** [review]

**Pull request merged**
