### PR TITLE
M-coloring Problem added

### PR DESCRIPTION
**Pull request by BamaCharanChhandogi**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

Added question

### CODE REVIEW

**Comment by debasishbsws** [comment]
Fix the formating mentioned in the Clang format linter
https://github.com/TheAlgorithms/Java/actions/runs/5766002343/job/15633103083?pr=4282#step:4:12:~:text=11-,%2D%2D%2D%20./src/test/java/com/thealgorithms/backtracking/MColoringTest.java%09(original),%7D,-Post%20Run%20actions

**Comment by BamaCharanChhandogi** [comment]
> Fix the formating mentioned in the Clang format linter https://github.com/TheAlgorithms/Java/actions/runs/5766002343/job/15633103083?pr=4282#step:4:12:~:text=11-,%2D%2D%2D%20./src/test/java/com/thealgorithms/backtracking/MColoringTest.java%09(original),%7D,-Post%20Run%20actions

Can You please tell me more? I don't understand this issue.

**Comment by BamaCharanChhandogi** [comment]
Hey, @debasishbsws The Whole code is running successfully. 
 I tried a lot but I don't understand what is actually problem!
 can you please check?

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Review by siriak — DISMISSED** [review]

**Review by siriak — APPROVED** [review]

**Pull request merged**
