### PR TITLE
Add Longest Subarray With Sum Less Than or Equal to K algorithm and t…

### PR DESCRIPTION
**Pull request by Chiefpatwal**
…ests

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by Chiefpatwal** [comment]
I have added the Longest Subarray with Sum Less Than or Equal to K algorithm along with its corresponding tests. However, I am encountering issues with the Infer run check, which is failing. I'm currently trying to understand the underlying causes of the failure. Any feedback or guidance would be greatly appreciated!

**Comment by siriak** [comment]
The issue with infer is that:
image

**Comment by siriak** [comment]
This issue also fails #6009

**Comment by Chiefpatwal** [comment]
> This issue also fails #6009

@siriak so clearly this is not my from my end ? besides how can i resolve this conflict...? any suggestions.

**Comment by siriak** [comment]
The infer check was fix, update your branch with the latest main and it should be fixed

**Comment by Chiefpatwal** [comment]
I have finally resolved the conflicts...already added test you may merge now.

**Comment by Chiefpatwal** [comment]
done @siriak

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
