### PR TITLE
[FEATURE] #4486  QuickSort Algo for LinkedList

### PR DESCRIPTION
**Pull request by Prabhat-Kumar-42**
Description : 
   - Added QuickSort Algorithm for Linked List.
   - Provided a detailed documentation in source-code file 

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by Prabhat-Kumar-42** [comment]
# QuickSort Feature Added for Linked List

Hey,

I added the QuickSort feature for linked lists. Please review it.

Although I have checked it for various test cases, if any issue arises, please let me know, and I will resolve it as soon as possible.

Thank you! 😊

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
Why did you add three files, and should that file remove the main method? I also added test cases.

**Comment by Prabhat-Kumar-42** [comment]
> Why did you add three files, and should that file remove the main method, also added test cases.

Yes, thank you for notifying me about the extra files. I really appreciate it. These are the files from other PRs I made in this repo.
I accidentally created the new feature branch from the previous working feature branch, instead of the master branch.
I removed the extra files.
Also, the main method is just for test cases, it can be safely removed, but I just left it there in case someone wanted to test the source code.

If there's anything else, please let me know.

**Comment by BamaCharanChhandogi** [comment]
Hello, please review the other LinkedList files to understand how to add different test case files. After adding test cases, you should remove the `main` method, as it is not needed.

Secondly, there is no need to create a `LinkedList class`. You are importing a package, so you can use it without declaring a `node` class.

**Comment by Prabhat-Kumar-42** [comment]
> Hello, please review the other LinkedList files to understand how to add different test case files. After adding test cases, you should remove the `main` method, as it is not needed.
> 
> Secondly, there is no need to create a `LinkedList class`. You are importing a package, so you can use it without declaring a `node` class.

Got it, Thank you for the review. Currently Working on the issues you mentioned.

**Comment by Prabhat-Kumar-42** [comment]
@BamaCharanChhandogi 
Please review the code.
Ignore the main method as it will be removed after building the test file.
If everything's alright with it then I will move to the build the test file.
Thank You !!

**Comment by Prabhat-Kumar-42** [comment]
@BamaCharanChhandogi 
Just a quick follow-up.
I have resolved the issues about extra-files, main method and added test code as you mentioned.
Please review the progress.
Let me know if something needs to be added.

Thank You !!

**Comment by BamaCharanChhandogi** [comment]
Looks good

**Comment by Prabhat-Kumar-42** [comment]
> Looks good

Thank You for the review.
This is if first time contributing to open-source. I hope I am doing alright and thank you for guiding me through this contribution @BamaCharanChhandogi.
If everything with the code seems fine to you, I would like to merge my PR.
I would humbly request the maintainer(s) to please merge my request using the "hacktoberfest-accepted" label.
That would be helpful to me.
Thank You !!

**Review by BamaCharanChhandogi — APPROVED** [review]
thanks!

**Pull request merged**
