### PR TITLE
improve Palindrome.java

### PR DESCRIPTION
**Pull request by lvncnt**
#96

### CODE REVIEW

**Comment by dynamitechetan** [comment]
Hi. Please resolve the conflicts.

**Comment by GammaBurst101** [comment]
Hey @dynamitechetan , I think I can resolve the conflict by making two public methods named "firstWay" and "secondWay". Therefore, both ways of finding the palindrome can be used. Should I do it and open a PR?

**Comment by dynamitechetan** [comment]
Sure @GammaBurst101

**Comment by GammaBurst101** [comment]
@dynamitechetan , I have a problem. @lvncnt wants to change Misc/Palindrome.java but there is no such class in Misc folder. There is PalindromePrime.java.
So, should I make a new .java file and do the two methods thing?
Sorry if I am asking questions like a moron but I am new to git and github.

**Comment by GammaBurst101** [comment]
@dynamitechetan , I have made a pull request #375 . Please take a look.

**Pull request closed without merging**
