### PR TITLE
Adding MinimumSpanningTree sorts

### LINKED ISSUE #4641: [FEATURE REQUEST] <Minimum Spanning Tree>
### What would you like to Propose?

I would like to add implementation of Minimum Spanning Tree under Sorting algorithm category.

### Issue details

Implementation of MST is missing under sorting algorithm category.

### Additional Information

I would like to Contribute to this repository.
So can you pls assign it to me.

### PR DESCRIPTION
**Pull request by Crayoncharle**
closes #4641 

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by Crayoncharle** [comment]
#4641

**Comment by Crayoncharle** [comment]
#4641

**Review by susanhsrestha — APPROVED** [review]

**Comment by Crayoncharle** [comment]
@BamaCharanChhandogi Hi, I'm doing my first open source community PR, and I'm excited to be a part of your project. But I know little about PR review, and I hope to go through your review earlier. That way I can see where my code is wrong or lacking, so I can fix it earlier. Thank you for taking time out of your busy schedule to look at my code.

**Comment by Crayoncharle** [comment]
Resolves #4641

**Review by BamaCharanChhandogi — COMMENTED** [review]
Hey, @Crayoncharle I think this code is already implemented here. 
https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/datastructures/graphs/Kruskal.java

**Pull request closed without merging**
