### PR TITLE
Random Range

### PR DESCRIPTION
**Pull request by Kwexy**
Creates and returns a random number within (and including) a range of numbers specified by the user.

### CODE REVIEW

**Comment by AppleteeYT** [comment]
Do you mean like from a scanner?

**Comment by Kwexy** [comment]
Possibly from a scanner. It's simply a method that takes 2 integer parameters and returns a random number within those 2 numbers.

**Comment by AppleteeYT** [comment]
[RandomNum.zip](https://github.com/TheAlgorithms/Java/files/4730975/RandomNum.zip)

**Comment by ayaankhan98** [comment]
Hey please make PR to master branch.

**Pull request closed without merging**
