### PR TITLE
surfaceAreaTriangle(fn_name_modified)

### PR DESCRIPTION
**Pull request by THIRU-1074**
---changing the function's identifier from **surfaceAreaTriangleRectangle** to **surfaceAreaTriangle**.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
Please also update tests

**Comment by THIRU-1074** [comment]
> Please also update tests

Yeah I have modified and commited.

**Comment by siriak** [comment]
Please see build logs, there are some errors Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/Java/Java/src/test/java/com/thealgorithms/maths/AreaTest.java:[39,32] cannot find symbol
  symbol:   method surfaceAreaTriangleRectangle(int,int)
  location: class com.thealgorithms.maths.Area
Error:  /home/runner/work/Java/Java/src/test/java/com/thealgorithms/maths/AreaTest.java:[84,75] cannot find symbol
  symbol:   method surfaceAreaTriangleRectangle(int,int)
  location: class com.thealgorithms.maths.Area
Error:  /home/runner/work/Java/Java/src/test/java/com/thealgorithms/maths/AreaTest.java:[86,75] cannot find symbol
  symbol:   method surfaceAreaTriangleRectangle(int,int)
  location: class com.thealgorithms.maths.Area

**Comment by THIRU-1074** [comment]
> Please see build logs, there are some errors Error: COMPILATION ERROR : [INFO] ------------------------------------------------------------- Error: /home/runner/work/Java/Java/src/test/java/com/thealgorithms/maths/AreaTest.java:[39,32] cannot find symbol symbol: method surfaceAreaTriangleRectangle(int,int) location: class com.thealgorithms.maths.Area Error: /home/runner/work/Java/Java/src/test/java/com/thealgorithms/maths/AreaTest.java:[84,75] cannot find symbol symbol: method surfaceAreaTriangleRectangle(int,int) location: class com.thealgorithms.maths.Area Error: /home/runner/work/Java/Java/src/test/java/com/thealgorithms/maths/AreaTest.java:[86,75] cannot find symbol symbol: method surfaceAreaTriangleRectangle(int,int) location: class com.thealgorithms.maths.Area

Thank you ! Siriak for guiding me ...Now all the checks have passed.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
