### PR TITLE
Added Exponential Moving Average Filter for audio signals , EMAFilter.java & EMAFilterTest.java

### PR DESCRIPTION
**Pull request by Shreya123714**
- [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [X] This pull request is all my own work -- I have not plagiarized it.
- [X] All filenames are in PascalCase.
- [X] All functions and variable names follow Java naming conventions.
- [X] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [X] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by Shreya123714** [comment]
Hi @yanglbme, @siriak, @vil02, @BamaCharanChhandogi, @alxkm, I’ve added an EMA filter implementation and some test cases in Java, but I'm running into a build error, could you please take a look when you have a moment? I’d appreciate any feedback or suggestions on how to resolve this.
Thank you so much! 🙏

**Comment by siriak** [comment]
This is the error
image

**Comment by Shreya123714** [comment]
@siriak , Thank you :) 
Resolved it 🥹.. Done

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by Shreya123714** [comment]
> Looks good, thanks!

Thank you, I will add more features to the repo in 2 or 3 days, I am planning to add, Fuzzy set and Fuzzy inference system as well 😄🌌🫡

**Pull request merged**
