### PR TITLE
Add method for minimum number of coins required for given amount

### PR DESCRIPTION
**Pull request by bansalKeshav**
@varunu28 can you please review this?
Thanks in advance.

### CODE REVIEW

**Comment by bansalKeshav** [comment]
@varunu28 or someone with write permission please review the PR

**Comment by bansalKeshav** [comment]
sure Should I just squashed the commit or make another PR?

**Comment by varunu28** [comment]
@bansalKeshav You can squash the commits. It would be easier to review the changes

**Comment by bansalKeshav** [comment]
@varunu28 Done, you can check.
Thanks for your fast response.

**Pull request merged**
