### PR TITLE
Order Agnostics Binary Search for Integer Arrays.

### PR DESCRIPTION
**Pull request by shahabrar7746**
- [*] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [*] This pull request is all my own work -- I have not plagiarized it.
- [*] All filenames are in PascalCase.
- [*] All functions and variable names follow Java naming conventions.
- [*] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
Could you please remove unrelated changes to linked list and add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

**Comment by shahabrar7746** [comment]
can u tell me how do can i add Junits to it?

**Comment by siriak** [comment]
You could take inspiration from here, the tests there are pretty similar to what you need https://github.com/TheAlgorithms/Java/blob/master/src/test/java/com/thealgorithms/searches/BinarySearch2dArrayTest.java

**Comment by HumbleFool830** [comment]
@shahabrar7746 are you working on this or can I move forward on this algorithm

**Pull request closed without merging**
