### PR TITLE
-determiant of a matrix (modified )

### PR DESCRIPTION
**Pull request by THIRU-1074**
---increased modularity by splitting up the code into three functions based on logic.
---increased the scalability of code as now it could work on numbers with any digits including  decimals ,negative numbers.
---enhanced the readability by following **Cofactor expansion** method which is **simple to implement** and **easy to understand**.(the algorithm is attached as a link)

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
Please replace tabs with spaces, remove main(), and add JUnit tests if there are none

**Comment by THIRU-1074** [comment]
Build got passed ,I have included test file to,help me with formatting ,I have converted tab to spaces but not working.............

**Comment by siriak** [comment]
You still have tabs committed in src/main/java/com/thealgorithms/maths/DeterminantOfMatrix.java. See linter job logs for more information
image

**Comment by THIRU-1074** [comment]
I have cleared those tab spaces still!!!! please guide me!

**Review by siriak — CHANGES_REQUESTED** [review]
Please add this formula in a separate file because it's different from the one in DeterminantOfMatrix or rename the original one to `Naive` and yours to `Cramers` if it's that

**Pull request closed without merging**
