### PR TITLE
Created AnyBaseToDecimal.java

### PR DESCRIPTION
**Pull request by varunu28**
An algorithm which can convert a given number of any base to its decimal value

### CODE REVIEW

**Comment by varunu28** [comment]
Kindly merge this commit or suggest if there are any changes to be made to the code.
Thanks

**Comment by r0hit-gupta** [comment]
@varunu28 Thanks!

**Comment by varunu28** [comment]
@r0hit-gupta  Thanks for the merge. 
Just a small request. I made this PR almost a month back and it took a month for the merge to happen. I suppose you need more moderators for this. Do let me know if you need any help.

I am looking forward to contributing to this repo and converting it into a one stop algorithm solution for Java programmers out there. More PRs coming your way :)

**Comment by r0hit-gupta** [comment]
@varunu28 we apologise for the delay. We are really looking forward to your PR's. Keep 'em coming and we might get you onboard as a moderator. Thanks! 😄

**Pull request merged**
