### PR TITLE
Create StalinSort.java

### PR DESCRIPTION
**Pull request by anant-jain01**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by anant-jain01** [comment]
@alxkm
@yanglbme 
@siriak 
@vil02 
@BamaCharanChhandogi 
please check and merge the pr with the hacktoberfest accepted tag.....
thank you

**Review by siriak — CHANGES_REQUESTED** [review]
Please remove main and add JUnit tests

**Comment by anant-jain01** [comment]
@siriak can you please tell me how to add JUnit tests?
thank you

**Review by siriak — COMMENTED** [review]
See https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms

**Pull request closed without merging**
