### PR TITLE
Add Compression Algorithm

### PR DESCRIPTION
**Pull request by shikhart98**
#96 
In this compression algorithm I have used Generic Heap. You will see there are 3 files (.java), in which first is Generic Heap, second is the compressClient (used to take input and display output) , third is the HEncoder , which have functions like compress and decompress ( these functions are called from the compressionClient ). Following are some screenshots of the running algorithm. 

1) Input 
inputcompress

2) Compressed Output
compressed

3) Checking the compressed output into Decompress function(we should get our previous input)
decompress

### CODE REVIEW

**Comment by dynamitechetan** [comment]
Hi @shikhart98  AnytoAny file does not end with a .java extension. Also there are no code comments. Can you please update this? Thanks ;)

**Comment by shikhart98** [comment]
Sure!
also see my compression algo please !

**Comment by dynamitechetan** [comment]
Hi. The Algorithm is good. Please add some comments and please remove the bin directory.

**Comment by shikhart98** [comment]
Hey I have added the comment to this code! kindly review and merge :)

**Comment by shikhart98** [comment]
Can anyone please review my code! its commented now!

**Pull request merged**
