### PR TITLE
updated CreateAndDetectLoop with test

### PR DESCRIPTION
**Pull request by albinsabu2023**
### Above algorithm helps to find the length of loop in linkedlist

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by siriak** [comment]
It's already present here https://github.com/TheAlgorithms/Java/blob/b61c54797babbe46825586894d69715d8947d559/src/main/java/com/thealgorithms/datastructures/lists/CreateAndDetectLoop.java#L5. Please improve the existing implementation (remove main, add tests, etc.)

**Review by siriak — CHANGES_REQUESTED** [review]
Please add JUnit tests and fix PR build and Clang checks

**Comment by albinsabu2023** [comment]
bro i have added unit test .But struggling to figure out the  issues with clang and build .Can you help me with that. In my system I have installed jdk22 is that an issue ?cause i seen v21 in pom

**Comment by albinsabu2023** [comment]
added unit test and fixed build issues can you please help with lint issue

@siriak

**Comment by albinsabu2023** [comment]
sorry for this much commit :) ,As I am a beginner I took Lot of time to figure out the issues .Hopefully this will be good to go 
can you please review and add hacktoberfest and hacktoberfest-accepted label with this pr. @siriak

**Comment by albinsabu2023** [comment]
Am i missing something ? Cuz I didnt get any response @arindam89  @siriak  @BurkHufnagel

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
