### PR TITLE
Refactorized ClosestPair.java to compliance with java sun rules

### PR DESCRIPTION
**Pull request by MarisaAfuera**
- Renamed package ClosestPair by closestpair
- Changed line BufferedReader in = new BufferedReader(new FileReader("closestpair\closest_data.txt"));, because the txt file wasn't found.
- Some casts to double have been deleted
- Added coments in javadoc format
- Add try finally blocks to close the text file
- Reduce every line to 80 characters
- Some function paramenters deleted because unused
- Refactorized bruteForce function to simplify code

### CODE REVIEW

**Comment by MarisaAfuera** [comment]
I delete some files. First I prefer to finish ClosestPair.java refactorization.  Is everything right?

**Comment by varunu28** [comment]
I would prefer if you merge all commits into one so that it is easier to review. Thanks

**Comment by MarisaAfuera** [comment]
@varun I don't know to merge all commits into one. Could you help me?

**Comment by varunu28** [comment]
@MarisaAfuera cd into the local fork on your machine and type ```git log --pretty=oneline```. The top commits would be the one made by you. If they are continuous commits then type ```git rebase -i HEAD~4```(Here I am taking an example of 4. It may change in your case). Doing this would open your default text editor and you can enter squash(s) in front of the commits you want to squash. Enter a commit message and then do a ```git push -f```.

Here is a [Video](https://www.youtube.com/watch?v=2E23I9PzplM&) which helped me learn the merge process. You can have a look

**Comment by MarisaAfuera** [comment]
@Varun I think pull request is now right. Let me know if you meet some
problem.

**Pull request closed without merging**
