### PR TITLE
Adding Dijkstra algorithm.

### PR DESCRIPTION
**Pull request by abdorah**
### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by prashantdoshi28 — CHANGES_REQUESTED** [review]
Please add code documentations.

**Comment by abdorah** [comment]
> Please add code documentations.

Ah ok I am working on them right now. But I have for the moment a readme file  that explains how the project works I will drop it here in the comment below

**Review by abdorah — COMMENTED** [review]
I just submitted the full code of dijkstra algorithm and reviewed the code. You can check my submission now. Thank you!

**Comment by ayaankhan98** [comment]
Hey please make PR to master branch.

**Pull request closed without merging**
