### PR TITLE
Refactorized ClosestPair.java in order to be compliant with java sun rules

### PR DESCRIPTION
**Pull request by MarisaAfuera**
Refactorized ClosestPair.java: adding commets, eliminating unuseful parameters, reorganizing code lines to be less than 80 characteres, each variable declaration in one line.

I've deleted txt file to provide input data.

I've created a unit test class. To complete the tests I've created a auxiliary type Location.

### CODE REVIEW

**Comment by varunu28** [comment]
@MarisaAfuera You can add the algorithm to the master right now but we are adding tests to Development branch in order to avoid confusion. So you can do either of the two below mentioned things:

 - Add only algorithm to master
 - Add algorithm and test both to Development and it will be merged to master in future.

Avoid creating another class for location. You can put it up in same file

**Comment by MarisaAfuera** [comment]
Yes varun. I was busy. Next weekend I will fix It.

**Comment by MarisaAfuera** [comment]
I think I've made the requesting changes. Now in files changed tab only is showed ClosestPair.java. No test neither Location class are available.

Also I squash the commits with git rebase. @varunu28  Is everything right?

**Comment by MarisaAfuera** [comment]
Hi,
@Varun I've made the requested changes. I everything right?

**Pull request merged**
