### PR TITLE
Moved StackPostfixNotation.java from the Others section to the Stack section

### PR DESCRIPTION
**Pull request by beradeep**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

## Issue
May solve issue #4360

### CODE REVIEW

**Review by vil02 — CHANGES_REQUESTED** [review]
I am not convinced if an algorithm using a stack should be in the `stacks` directory. If it should be, then all of the algorithms using any data structure should be in the `datastructures` directory.

My understanding is that the `stacks` should contain different implementations of stack.

**Comment by beradeep** [comment]
I think since this one is closely related to the application of stack, and that there are already algorithms like `PostfixToInfix.java` inside `stacks`, so moving `StackPostNotation.java` into `stacks` makes sense according to me.

**Comment by BamaCharanChhandogi** [comment]
> I think since this one is closely related to the application of stack, and that there are already algorithms like `PostfixToInfix.java` inside `stacks`, so moving `StackPostNotation.java` into `stacks` makes sense according to me.
> 

Exactly

**Comment by beradeep** [comment]
So can it be merged?

**Comment by siriak** [comment]
Let's create a directory `stack` in `agorithms` directory and put stack-related algorithms there. They shouldn't be in `datastructures`. Besides, please also update file structure of tests to match that of algorithms

**Comment by BamaCharanChhandogi** [comment]
@beradeep are you working?

**Comment by beradeep** [comment]
I have tried to incorporate all the requested changes. Is it okay right now?

**Review by siriak — APPROVED** [review]

**Review by vil02 — APPROVED** [review]

**Pull request merged**
