### PR TITLE
Added comments before the constructors

### PR DESCRIPTION
**Pull request by DeveshBaranwal**
Added comments before all the constructors which implies what the constructor will do.

### CODE REVIEW

**Comment by DeveshBaranwal** [comment]
Request you to merge my PR and label it as hacktoberfest - accepted

**Comment by deadshotsb** [comment]
These are all minor changes and are not required kindly follow instructions of hacktoberfest

**Comment by DeveshBaranwal** [comment]
But the instructions of Hacktoberfest says that all PRs on or before 3rd of
October will be considered.

**Comment by deadshotsb** [comment]
No, the review period and making pr in specified repo have changed but the criteria for accepting a pr remains the same.

**Pull request closed without merging**
