### PR TITLE
Creating FourSumProblem 

### PR DESCRIPTION
**Pull request by HimanshuMahto**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [ ] I created FourSumProblem as per the issue using Brute Force, two pointer approach, and HashMap approach as well.

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Hi, please write only one approach with good time complexity. You don't need to write all approaches. Also, remove the main method and add test cases

**Comment by HimanshuMahto** [comment]
Got it

**Comment by HimanshuMahto** [comment]
> Hi, please write only one approach with good time complexity. You don't need to write all approaches. Also, remove the main method and add test cases

Like how do I add testcase in the form of comments or to the main method.

**Comment by vil02** [comment]
It is a duplicate of #4408 (cf. [this comment](https://github.com/TheAlgorithms/Java/pull/4408#issuecomment-1742018030)).

**Pull request closed without merging**
