### PR TITLE
Added Fisher-Yates Shuffle

### PR DESCRIPTION
**Pull request by PolyCole**
### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by shellhub** [comment]
@cclauss Can you see why this action build failed. 
> remote: Permission to TheAlgorithms/Java.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/TheAlgorithms/Java/': The requested URL returned error: 403

**Comment by cclauss** [comment]
A first-time contributor is not going to have write access to the repo.

**Comment by shellhub** [comment]
> A first-time contributor is not going to have write access to the repo.

How to solve this problem ? 

> A first-time contributor is not going to have write access to the repo.

How to solve this problem. I want to format code using google java formatter when PR is created. Why update_directory action worked for a first-time contributor

**Comment by cclauss** [comment]
Perhaps because of these two lines:
https://github.com/TheAlgorithms/Java/blob/master/.github/workflows/update_directory_md.yml#L8-L9

Actions have moved from `master` to `main` which probably means that checkout is @v1 instead of @v2.  The older versions allowed more rewriting to a PR while later versions stopped that for _security_ reasons.

**Comment by PolyCole** [comment]
Is there anything I can do on my end to make your lives easier or help resolve this?

**Comment by cclauss** [comment]
Yes.  Please look at the output of the failing test and reformat your code so it looks like the + lines.  If you do so, the test should pass.  This is supposed to be automatic but in a pinch, manual modifications will do.  Thx.

**Comment by PolyCole** [comment]
Was foolish and removed my local fork. Going to close and re-open PR.

**Pull request closed without merging**
