### PR TITLE
Feature quick select

### PR DESCRIPTION
**Pull request by Nils-Goldmann**
### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

[Wikipedia Entry](https://en.wikipedia.org/wiki/Median_of_medians)

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.

### CODE REVIEW

**Comment by Nils-Goldmann** [comment]
There are two automatic checks that failed: Build and Prettify.

Build uses javac as a compiler in build.yml, while my colleague and I compiled using Maven. I am pretty sure that this is the reason for the failure. How should we proceed on this? We could change build.yml accordingly, if this is an option for you.

Also, Prettify failed and it is not quite obvious to me why. Do you maybe have an idea what the reason could be?

**Comment by siriak** [comment]
The prettier is just faulty, nvm

**Comment by siriak** [comment]
I've changed builds to maven, the verify command used should run your tests, right?

**Comment by Nils-Goldmann** [comment]
> I've changed builds to maven, the verify command used should run your tests, right?

During our work, we used the test command, but verify also seems to work.

**Review by siriak — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
