### PR TITLE
ProjectEuler solution to Problem 5 

### PR DESCRIPTION
**Pull request by LoopGlitch26**
### **Added Project Euler Problem 5 solutions**

Trying out to contribute to Open Source and The Algorithms Organization

#### References

My own repo that I wrote for my college club: https://github.com/LoopGlitch26/Project-Euler-Solutions

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.

### CODE REVIEW

**Comment by Likenttt** [comment]
remember to format code with google java formatter

**Comment by LoopGlitch26** [comment]
@Likenttt can you please tell me how can I do that? It seems the format is wrong in question 8 only

**Comment by Likenttt** [comment]
> @Likenttt can you please tell me how can I do that? It seems the format is wrong in question 8 only

Which IDE are you using? Mine is Intellij IDEA.
1. Use `Command` + `,` to open settings. Search "google-java-format" in the menu `Plugins` and install it.
2. Restart IDEA.
3. Open Settings →Other Settings→Default Settings and enable it for the current project, in which case the command "Code → Reformat code" will be replaced with google style.

**Comment by Likenttt** [comment]
> @Likenttt can you please tell me how can I do that? It seems the format is wrong in question 8 only

看了下你的删除的代码,  问题应该出在格式化工具配置上. 在我本地,格式化以后代码是这样的.

```
public class Test {
  public static void main(String[] args) {
    String S =
        "7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450";
    long p = 0L;
    for (int i = 0; i < S.length() - 13; i++) {
      long q = 1L;
      for (int j = i; j < i + 13; j++) {
        q *= Integer.parseInt(S.substring(j, j + 1));
      }
      if (q > p) {
        p = q;
      }
    }
    System.out.println(p);
  }
}

```

**Pull request closed without merging**
