### PR TITLE
This is a big update for Algorithms, working classes, no one class or method was broken

### PR DESCRIPTION
**Pull request by Faktorealchik**
_Firstly_, **all classes now we can use**, when I take this, I can`t use all classes. 
_Secondly_, I deleted **unuseful comments**, code became more cleaner,
_Thirdly_, where I can, I **renamed** methods and variables, so code became more cleaner too, 
Next - I replaced all **"main" methods** in all classes into **test methods**, added .pom,
**update gitignore**, so now you can add tests to your classes,
Some methods I replaced in style Java 8, so now it easily to read
I tried to use style of programming like in Java, not in C++ or else, so people, who use Java, will like it(maybe)

I think, it will be a good update, but it will depend on your mind

### CODE REVIEW

**Comment by dynamitechetan** [comment]
can you please resolve conflicts?

**Comment by Faktorealchik** [comment]
About which conflicts are you talking?

**Comment by dynamitechetan** [comment]
on this page you can see there is a message that this branch has conflicts that must be resolved.

**Comment by Faktorealchik** [comment]
I resolve it, by add a commit in every conflict, now it`s better? What I should do now? Can you please check this?

**Comment by Faktorealchik** [comment]
any problems now? I have already commited code.

**Pull request closed without merging**
