### PR TITLE
Addition of a few new codes in strings, Misc, Maths and DataStructures/Graphs folders.

### PR DESCRIPTION
**Pull request by AzadN**
### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by AzadN** [comment]
Hello @shellhub,
Could you please help me out by reviewing my pull request and merging it if the codes are useful since there hasn't been any update since I issued this pull request? I tagged you since you have done the most recent successful merges :) I actually was supposed to contribute to open-source regarding an assignment in my Master's course Software Architecture and the deadline is 7th November so it would be really nice if my changes could be merged into the original repo ASAP. Also, I don't really get why one of the 4 checks i.e. code formatter one failed :(

**Comment by AkMo3** [comment]
@AzadN Sure, would love to review your PR. I stopped reviewing PR as they where not being merged, and instead started to work myself to create a repo sort of this. Also, if your code formatter test are not being passed, try running the following commands- 
1. `wget https://github.com/google/google-java-format/releases/download/google-java-format-1.9/google-java-format-1.9-all-deps.jar -O formatter.jar`
2. `java -jar formatter.jar --replace --set-exit-if-changed {FILE_NAME.java}` .

I would start detailed reviewing by today evening, just give me some time.

**Comment by AzadN** [comment]
> @AzadN Sure, would love to review your PR. I stopped reviewing PR as they where not being merged, and instead started to work myself to create a repo sort of this. Also, if your code formatter test are not being passed, try running the following commands in terminal or powershell in folder -
> 
> 1. `wget https://github.com/google/google-java-format/releases/download/google-java-format-1.9/google-java-format-1.9-all-deps.jar -O formatter.jar`
> 2. `java -jar formatter.jar --replace --set-exit-if-changed {FILE_NAME.java}` .
> 
> I would start detailed reviewing by today evening, just give me some time.

Sure. By the way, that code formatter check has suddenly disappeared from the total checks done don't know how :)

**Comment by shellhub** [comment]
So many files changes. Can you create PR for each files. So it will be easy to review.

**Comment by AzadN** [comment]
> So many files changed. Can you create PR for each file. So it will be easy to review.

So shall I close this current PR and issue separate PRs for each file added in this PR?

**Comment by shellhub** [comment]
Yes. And add documentation to source code. and test using `assert` . Please this test example: https://github.com/TheAlgorithms/Java/blob/master/Maths/Factorial.java#L7

**Comment by AzadN** [comment]
@AkMo3 sorry buddy, have to close this PR to issue separate PR per file. Hope you didn't start reviewing already.

**Pull request closed without merging**
