### PR TITLE
Update CheckVowels.java

### PR DESCRIPTION
**Pull request by utkarsh2004git**
Optimized the code by extending the Set elements

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by utkarsh2004git** [comment]
Optimized the code for src/main/java/com/thealgorithms/strings/CheckVowels.java

**Comment by RadSparkle** [comment]
.

**Comment by RadSparkle** [comment]
.

**Comment by siriak** [comment]
The original code is fine, not worth optimizing in this way in my opinion, but thanks for the suggestion anyway!

**Pull request closed without merging**
