### PR TITLE
FourSumProblem

### PR DESCRIPTION
**Pull request by ankity26**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by vil02** [comment]
Please do not use the `main` method. I think in this case, `FourSumProblem` can be a _utility class_. And please add unit tests of your class. I a good examples to look at are [`Factorial`](https://github.com/TheAlgorithms/Java/blob/34cf6dab28ee2271fbf228d345bcf14db85c211c/src/main/java/com/thealgorithms/maths/Factorial.java) and [`FactorialTest`](https://github.com/TheAlgorithms/Java/blob/34cf6dab28ee2271fbf228d345bcf14db85c211c/src/test/java/com/thealgorithms/maths/FactorialTest.java).

**Comment by BamaCharanChhandogi** [comment]
Do not need to write all time complexity code.
Just write one best TC.

**Comment by lMrAlgorithml** [comment]
Viernes banco plano con 40 kilos 10 x 4 series.       Press en el banco a
45÷ con mancuernas de 10 kilos apertura en banco plano 10 en seguidilla un
corto de apertura también de 10 4 series con 5 kilos barra W bicep entera
con 10 kilos y neutro en barra bíceps con 5 4 series de en aumento
10/12/14/16

**Comment by ankity26** [comment]
i am working on test cases. Order of elements is giving error , and how many test cases do i need to add ?

**Comment by vil02** [comment]
> i am working on test cases. Order of elements is giving error , and how many test cases do i need to add ?

I think you can start by adding _any_. During the process we will add some more.

In general, very _roughly speaking_, in order to have all branches covered by tests, the number of test cases should be proportional to cyclomatic complexity.

**Comment by BamaCharanChhandogi** [comment]
Hello, Your code does not work properly. duplicate lists are generated.
 `nums: [2,2,2,2,2], target: 8`

**your output like:** `[[2, 2, 2, 2], [2, 2, 2, 2]]`

**Comment by vil02** [comment]
It is a duplicate of #4408 (cf. [this comment](https://github.com/TheAlgorithms/Java/pull/4408#issuecomment-1742018030)).

**Pull request closed without merging**
