### PR TITLE
Optimize and Format Knapsack Memoization Algorithm

### PR DESCRIPTION
**Pull request by Chiefpatwal**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by Chiefpatwal** [comment]
This pull request fixes the bug in the KnapsackMemoization class by removing unused imports and optimizing the memoization logic.

**Comment by siriak** [comment]
Could you add JUnit tests that cover the code you have changed?

**Comment by Chiefpatwal** [comment]
> Could you add JUnit tests that cover the code you have changed?

sure

**Comment by Chiefpatwal** [comment]
I have added test 4 and test 5 for the same.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
