### PR TITLE
Implement solution for bounded coin change problem

### PR DESCRIPTION
**Pull request by abhisheksharma886**
- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Review by siriak — COMMENTED** [review]
Looks like it's a duplicate of https://github.com/TheAlgorithms/Java/blob/4effd28d80faa64087c2cbb94f106e5be61b7324/src/main/java/com/thealgorithms/dynamicprogramming/CoinChange.java

**Comment by abhisheksharma886** [comment]
@siriak It is a different version of this question where number of coins are fixed

**Comment by siriak** [comment]
image
image
They both look exactly the same to me

**Comment by abhisheksharma886** [comment]
Bro Sorry there is some confusion from my side

**Pull request closed without merging**
