### PR TITLE
Algorithm to search for an element in 2D Array.

### PR DESCRIPTION
**Pull request by Shashwat79802**
The algorithm searches for an element in a 2D array sorted in both row & column manner. The algorithm's implemented over binary search. Added it's jUnit test too.

### CODE REVIEW

**Comment by aitorfi** [comment]
Could you add an interface similar to [SearchAlgorithm](https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/devutils/searches/SearchAlgorithm.java) that can be used to search a matrix and implement it in your algorithm?

**Comment by Shashwat79802** [comment]
Actually haven't studied Interface yet, is it really necessary?

**Comment by aitorfi** [comment]
Alright I'll implement the interface once this PR is merged. One more thing, method names must be in cammelCase will you fix that please?

**Comment by Shashwat79802** [comment]
Made the changes you asked, and will make more if needed.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
