### PR TITLE
Added algorithm for swapping linkedlist nodes

### PR DESCRIPTION
**Pull request by Aashu-11**
The above algorithm helps in swapping nodes of linkedlists.

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by Aashu-11** [comment]
@owners please review and merge my request.

**Comment by Aashu-11** [comment]
@alxkm @BamaCharanChhandogi @siriak @yanglbme @vil02 please look after and merge my request

**Comment by Aashu-11** [comment]
Hello...please approve my request and kindly merge it

**Review by siriak — CHANGES_REQUESTED** [review]
Please remove printList and main methods, and add JUnit tests instead. And also check PR checks

**Pull request closed without merging**
