### PR TITLE
Update Pangram.java

### PR DESCRIPTION
**Pull request by preritasaini1**
Updated the Pangram.java file by adding a bitwise approach and improving code readability

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by preritasaini1** [comment]
Hello everyone, I am ne in this contributing world, just checking in on my pull request. I'm excited to learn from your feedback and improve my contributions. Thanks!

**Comment by preritasaini1** [comment]
I am really sorry i forget to add the label of "Hacktoberfest-accepted" . Please accept it .

**Review by siriak — CHANGES_REQUESTED** [review]
Please replace main with JUnit tests

**Review by preritasaini1 — COMMENTED** [review]
I replaced main with JUnit tests. Please check and review . Thanks!

**Review by siriak — CHANGES_REQUESTED** [review]
Now PR checks fail
image

**Pull request closed without merging**
