### PR TITLE
Create PlusOne.java

### PR DESCRIPTION
**Pull request by adjamalbek**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by debasishbsws** [comment]
Add some JUnit Test

**Comment by adjamalbek** [comment]
> Add some JUnit Test
I did 
https://github.com/TheAlgorithms/Java/pull/3711

**Comment by adjamalbek** [comment]
test and main are combined, camel case errors and class names were fixed, please review kindly

**Comment by adjamalbek** [comment]
errors were fixed

**Comment by adjamalbek** [comment]
Requesting review from @siriak and @yanglbme and @debasishbsws for approval and merging.

**Comment by siriak** [comment]
This is also a typical primary school algorithm where you need to keep track of carry, so that's not a computer science problem

**Pull request closed without merging**
