### PR TITLE
Added Space Optimized Solution to Subset sum problem 

### PR DESCRIPTION
**Pull request by Rupa-Rd**
Solved #5600 

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Review by siriak — COMMENTED** [review]
There are no files changed in this PR

**Comment by Rupa-Rd** [comment]
> There are no files changed in this PR

Kindly verify it!

**Review by siriak — COMMENTED** [review]
Please add JUnit tests

**Comment by Rupa-Rd** [comment]
> Please add JUnit tests

@siriak Added JUnit test.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
