### PR TITLE
Fixed multiple typos, and minor syntax issues.

### PR DESCRIPTION
**Pull request by kodaman2**
##  **No Folder/**

_**Huffman.java**_
- Fixed formatting. Indentation and tabs was missing.

**_Insert_delete_in_array.java_**

- Fixed class name.

## **Conversions/** 

_**DecimalToHexaDecimal.java**_

- Fixed incorrect class name from Test to DecimalToHexaDecimal.
- Fixed string variables and missing semicolon.
- Formatted the class correctly due to missing indentation.
- Fixed the main method, the example was using hardcoded decimal value instead of user input.
- Tested user input and hexadecimal output was correct.

_**DecimalToOctal.java**_

- Fixed class name.

_**HexaDecimalToBinary.java**_

- Fixed class name.
- Fixed main method. Instance creation was calling the wrong class name.
- Tested the class.

## **Misc/**

_**CountTheWords.java**_

- Fixed CountTheWords.java file name.

_**Dijkshtra.java**_

- Fixed Dijkshtra.java class name.
- Organize missing imports.

_**ReverseString.java**_

- Fixed main method, calling wrong static class.

_**Class names fixed on below classes.**_
root_precision
TowerOfHanoiUsingRecursion
interpolationSearch
radixSort
BinaryTreeSort
AVLTree
RodCutting

_**Classes not running:**_
OctalToBinary.java
Abecedarian.java
BinaryTreeSort.java missing imports.

### CODE REVIEW

**Comment by fredz0003** [comment]
**Conversions/OctalToBinary.java**

The algorithm was started from scratch. I've placed credit at the top to the author. It looks like whoever push the last OctalToBinary was a very bad CTRL+V, CTRL+C and the worse is it wasn't even properly tested.

I've tested against several Octal numbers and double checked with an two online conversion tools. In my opinion this algorithm is much better since it is actually doing the calculations manually rather than using built in java methods.

**Comment by christianbender** [comment]
@kodaman2 You must resolve your conflicts then I can merge your pull request.

**Comment by kodaman2** [comment]
It might be a good idea to cancel this PR at the time of commit there were no merge issues. I have no time to go back and undue all the fixes I've done.

**Comment by christianbender** [comment]
@kodaman2 I understand.

**Pull request closed without merging**
