### PR TITLE
Add `LotteryScheduling` new algorithm with Junit tests

### PR DESCRIPTION
**Pull request by Hardvan**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Review by siriak — DISMISSED** [review]

**Review by siriak — APPROVED** [review]

**Comment by siriak** [comment]
Please fix infer PR check

**Comment by Hardvan** [comment]
I think the infer check is failing because I added a new dependency (mockito) in the pom.xml file. Mockito is needed for mocking the random number generator in the test cases.

**Comment by siriak** [comment]
It says
src/main/java/com/thealgorithms/scheduling/LotteryScheduling.java:56: error: Null Dereference(NULLPTR_DEREFERENCE)
  `selectedProcess` could be null (from the call to `LotteryScheduling.selectProcessByTicket(...)` on line 54) and is dereferenced. 
  54.               Process selectedProcess = selectProcessByTicket(winningTicket);
  55.   
  56. >             selectedProcess.setWaitingTime(currentTime);
  57.               currentTime += selectedProcess.getBurstTime();
  58.               selectedProcess.setTurnAroundTime(selectedProcess.getWaitingTime() + selectedProcess.getBurstTime());

**Comment by Hardvan** [comment]
I have fixed the bug.

**Review by siriak — APPROVED** [review]

**Pull request merged**
