### PR TITLE
MinMax AI tic-tac-toe

### PR DESCRIPTION
**Pull request by kunal232i**
### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ] All new Java files are placed inside an existing directory.
- [ ] All filenames are in all uppercase characters with no spaces or dashes.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by kunal232i** [comment]
can you give this PR as hacktoberfest Tag..?

**Review by siriak — CHANGES_REQUESTED** [review]
Please remove .gitpod.yml and driver code and add JUnit tests. Isn't that dynamic programming?

**Comment by kunal232i** [comment]
> Please remove .gitpod.yml and driver code and add JUnit tests. Isn't that dynamic programming?

Yeah sure, I'll do it ASAP.
Yes it comes under DP.

**Comment by kunal232i** [comment]
> Please add JUnit tests and replace user input with function parameters
Ok

**Pull request closed without merging**
