### PR TITLE
Added Order Agnostic Binary Search problem in Searches folder.

### PR DESCRIPTION
**Pull request by ThisIsNishanth**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Review by VishwaS-22 — DISMISSED** [review]
Hey @ThisIsNishanth! Your code looks good to me! I too solved this problem with the same approach. Thanks for contributing. Happy Contributions.

Thankyou!

**Review by debasishbsws — CHANGES_REQUESTED** [review]
remove the main function and add some JUNIT tests. 
you can refer to this: https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms/searches

you can also remove redundancy in the code. for order Agnostic only some code is need to be inside the condition. not all of it.

**Comment by ThisIsNishanth** [comment]
Hey @debasishbsws, I am sorry for all these commits. I am new to JUnit and this repo, so I had to understand the errors and pass all checks. I committed all those changes in order to pass the "Build With Maven" checks. I have successfully passed all checks now. I have added a main folder and a test folder. Main folder has the non-redundant code and the test folder has the JUnit tests. Thank you for your suggestions!

**Review by debasishbsws — APPROVED** [review]
looks good. thank you for contributing

**Pull request merged**
