### PR TITLE
Rabin karp algo

### PR DESCRIPTION
**Pull request by Lohit-pro**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by Lohit-pro** [comment]
Hey regarding the previous comment on my previous closed PR @alxkm , my implementation improves the Rabin-Karp algorithm by more modularity with well-structured methods, making the code more readable and maintainable. It includes input error handlings to prevent runtime errors from edge cases like empty strings.. I faced small small errors after committing so there are more commits :)

**Review by BamaCharanChhandogi — COMMENTED** [review]
Remove `main` method, and add test cases separately.

**Comment by vil02** [comment]
There are already two implementations:
- [`RabinKarp.java`](https://github.com/TheAlgorithms/Java/blob/648572a8c53540d64de52a4692d7c13ff81a4cb9/src/main/java/com/thealgorithms/strings/RabinKarp.java),
- [`RabinKarpAlgorithm.java`](https://github.com/TheAlgorithms/Java/blob/648572a8c53540d64de52a4692d7c13ff81a4cb9/src/main/java/com/thealgorithms/searches/RabinKarpAlgorithm.java).

**Comment by Lohit-pro** [comment]
> There are already two implementations:
> 
> * [`RabinKarp.java`](https://github.com/TheAlgorithms/Java/blob/648572a8c53540d64de52a4692d7c13ff81a4cb9/src/main/java/com/thealgorithms/strings/RabinKarp.java),
> * [`RabinKarpAlgorithm.java`](https://github.com/TheAlgorithms/Java/blob/648572a8c53540d64de52a4692d7c13ff81a4cb9/src/main/java/com/thealgorithms/searches/RabinKarpAlgorithm.java).

👀why there are two implementations then? just asking 😀
is it allowed? if yes, make this the third one :)

**Comment by vil02** [comment]
> 👀why there are two implementations then?

No idea.

> is it allowed?

No.

**Comment by BamaCharanChhandogi** [comment]
Yeah, you can improve the existing algo, I can not add this algo, it already exists.

**Pull request closed without merging**
