### PR TITLE
Directory.md

### PR DESCRIPTION
**Pull request by Shashwat79802**
Updated the **Directory.md** file, and added all the recently added programs to both main and test package.

### CODE REVIEW

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by Shashwat79802** [comment]
Will I not get the _**Hacktoberfest-accepted**_ tag for this one?

**Comment by siriak** [comment]
The repository itself is tagged for hacktoberfest, so PR tag is redundant as I understand

**Comment by JYOTI73** [comment]
package com.thealgorithms.datastructures.heaps;

/*
 * @author Nicolas Renard Exception to be thrown if the getElement method is
 * used on an empty heap.
 */
@SuppressWarnings("serial")
public class EmptyHeapException extends Exception {

    public EmptyHeapException(String message) {
        super(message);
    }
}

**Pull request merged**
