### PR TITLE
Fixed #2941

### LINKED ISSUE #2941: Variable type writing error
**Describe the bug**
Variable type writing error

**To Reproduce**

1. Go to 'Java/src/main/java/com/thealgorithms/datastructures/trees'
2. Click on 'AVLSimple'
3. Scroll down to 'Line 85'

**Expected behavior**
Modify variable “Strings” to “String”

**Screenshots**
image

**Device Specification**

**Additional context**

### PR DESCRIPTION
**Pull request by Boris-Chang**
### **Describe your change:**

- [ ] Add an algorithm?
- [x] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by siriak** [comment]
The problem was that the .java extension was missing. I've added it and now the build fails, could you take a look and fix the remaining issues? Here are relevant log entries:
Error:  /home/runner/work/Java/Java/src/main/java/com/thealgorithms/datastructures/trees/AVLSimple.java:[32,8] class AVLTree is public, should be declared in a file named AVLTree.java
Error:  /home/runner/work/Java/Java/src/main/java/com/thealgorithms/datastructures/trees/AVLTree.java:[3,8] duplicate class: com.thealgorithms.datastructures.trees.AVLTree

**Review by Boris-Chang — COMMENTED** [review]
Rename class AVLTree to class AVLSimple

**Comment by Boris-Chang** [comment]
Fixed #2948

**Review by siriak — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
