### PR TITLE
Created a file for tiling problem

### PR DESCRIPTION
**Pull request by kartikay23**
### **Describe your change:**
Created a file on tiling problem solving using divide and conquer algo.

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
Please add a problem statement with a link to Wikipedia or a different known website

---
**Sema Reaction:** :hammer_and_wrench: This code needs a fix

**Comment by kartikay23** [comment]
Hi, I have added the problem statement and the link for reference.

**Comment by siriak** [comment]
Could you update your PR with the latest code from master? Project structure has changed a bit since this PR was open

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Comment by siddhant2002** [comment]
Can I work under this issue?

Basically I've to create a pr for the tiling problem?

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Comment by kartikay23** [comment]
Okay. You may work on the issue.

**Pull request closed without merging**
