### PR TITLE
UPDATE README.md

### PR DESCRIPTION
**Pull request by Aman28801**
Added Types of Queue in Readme.md

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by Aman28801** [comment]
@siriak plese review this pull request and requested to merge under hacktoberfest

**Comment by Aman28801** [comment]
@siriak please review this pull request and requested to merge under hacktoberfest

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by Aman28801** [comment]
can u please give hacktoberfest label

**Pull request merged**
