### PR TITLE
Added MatrixFastPower.java 

### PR DESCRIPTION
**Pull request by DDullahan**
Added MatrixFastPower.java
Other Matrix basic operator is based on @khalil2535

### CODE REVIEW

**Comment by DDullahan** [comment]
@varunu28  fixed  :-)

**Comment by DDullahan** [comment]
tks for your suggestions

**Comment by varunu28** [comment]
Thanks for the PR @DDullahan . I would encourage you to add the algorithms under Matrix to the Development branch along with the tests. Please follow the points mentioned in README of Development branch.

**Comment by DDullahan** [comment]
Got it.  I will follow this in my next pr. 
Thanks again :-)

**Comment by varunu28** [comment]
@DDullahan Just make sure the PR is against the Development branch

**Pull request merged**
