### PR TITLE
Update MinimumPathSum.java

### PR DESCRIPTION
**Pull request by chinnuteja**
- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by chinnuteja** [comment]
This my first contribution to open source .
let me know if i did any thing wrong
and also guide me in a right path.

**Comment by BamaCharanChhandogi** [comment]
> This my first contribution to open source . let me know if i did any thing wrong and also guide me in a right path.

Hi @chinnuteja, Why do you want to update the code?

**Comment by Manan-09** [comment]
Hi @chinnuteja , Congratulation for starting open source journey.
However as @siriak mentioned , we should not update input grid , it's not the best practice to modify input.
And for this issue , I have already raised PR. You can checkout other code and come up with improvements in time complexity or space complexity or some bug fixes.

**Comment by siriak** [comment]
This was updated in a different PR. Please resolve conflicts and open a new PR if needed

**Pull request closed without merging**
