### PR TITLE
add Stack , ArrayStack & ArrayStackTest

### PR DESCRIPTION
**Pull request by khalil2535**
- [x] create `Stack` interface.
- [x] create `ArrayStack` class.
- [x] create `ArrayStackTest` test class.

### CODE REVIEW

**Comment by varunu28** [comment]
@khalil2535 Please squash the commits into one for PR review

**Comment by varunu28** [comment]
@khalil2535 No worries. It's a great tool to have in your Git toolset. This is the [Video](https://www.youtube.com/watch?v=2E23I9PzplM&t=4s) which I referred to learn merging commits. Have a look and let me know if you need any help

**Comment by khalil2535** [comment]
@varunu28 Thanks , that's better now

**Comment by khalil2535** [comment]
@varunu28 Is there any problem in the pull request ?

**Comment by varunu28** [comment]
@khalil2535 I was unable to look into the changes due to some work. I would review it tonight. My bad.

**Comment by khalil2535** [comment]
Is it better now ? @varunu28

**Comment by khalil2535** [comment]
This pull request took a long time to be reviewed so i will close it.

**Pull request closed without merging**
