### PR TITLE
Added sort list Algorithm

### PR DESCRIPTION
**Pull request by siddhant2002**
### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
No need to include string compare algorithms, please replace main() with tests as in https://github.com/TheAlgorithms/Java/blob/98656cb0cdacd175559272bcbb8bc3b86ddac52a/src/test/java/com/thealgorithms/maths/KaprekarNumbersTest.java and improve formatting

**Comment by siddhant2002** [comment]
@siriak Please check the updated pr

**Review by siriak — CHANGES_REQUESTED** [review]
The formatting is much better, but you still need to replace main() with automated tests as mentioned in the previous review

**Comment by siddhant2002** [comment]
@siriak Please check the updated pr

**Comment by zhrgithub** [comment]
ok


| |
张泓锐
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年01月19日 12:28，Siddhant Swarup ***@***.***> 写道：

@siriak Please check the updated pr

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Review by siriak — APPROVED** [review]
Great, thanks!

**Pull request merged**
