### PR TITLE
feature: Adding MinSumKSizeSubarray in Sliding Window Algorithm

### PR DESCRIPTION
**Pull request by rashi07dashore**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
Please add JUnit tests

**Comment by rashi07dashore** [comment]
> Please add JUnit tests

@siriak please check. Thank you~

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by Chiefpatwal** [comment]
@rashi07dashore , @siriak the Algo added  by @rashi07dashore is already in there please take a look at it.

**Pull request merged**
