### PR TITLE
Implementation of Edmonds' Algorithm

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
issue #5447 

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by Brijeshthummar02** [comment]
hello @codecov-commenter i'm not getting exact error to solve.

**Comment by Brijeshthummar02** [comment]
hello there, @BurkHufnagel i request you to check the commit i've made.

**Comment by Brijeshthummar02** [comment]
review requested @qckzr, @arindam89 , @BurkHufnagel, @alxkm , @yanglbme , @vil02 , @siriak @yanglbme.

**Review by siriak — CHANGES_REQUESTED** [review]
The code looks good, could you please replace tests in the class with some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

**Review by siriak — CHANGES_REQUESTED** [review]
You need JUnit tests. See https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms

**Pull request closed without merging**
