### PR TITLE
Createmedianoftwosortedarray

### PR DESCRIPTION
**Pull request by tangorishi**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
Please add JUnit tests

**Comment by tangorishi** [comment]
added Junit test

**Review by siriak — CHANGES_REQUESTED** [review]
Both the source code and tests must be present in appropriate places in the project hierarchy and have .java extension. Please take a look at other merged pull requests for reference

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Pull request closed without merging**
