### PR TITLE
CountFriendsPairing Algorithm Added

### PR DESCRIPTION
**Pull request by Deeeeksha**
### **Describe your change:**

- > Algorithm added in Dynamic Programming.
- > Test Cases of the algorithm also Added.

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ] All new Java files are placed inside an existing directory.
- [ ] All filenames are in all uppercase characters with no spaces or dashes.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Deeeeksha** [comment]
Hi @siriak . Is there any update on the issue? Kindly review the changes .

**Comment by Deeeeksha** [comment]
Hello @siriak and @yanglbme . Is there any update on the issue part ?? Kindly review the changes Please.

**Review by siriak — CHANGES_REQUESTED** [review]
Hi, sorry for the response time, was pretty busy. Could you add automated tests with the @Test thing? There are examples in the codebase. Also please add indentation where appropriate. Thanks!

**Comment by zhrgithub** [comment]
sorry, I have not time.


| |
张泓锐
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年01月17日 03:36，Andrii ***@***.***> 写道：

@siriak requested changes on this pull request.

Hi, sorry for the response time, was pretty busy. Could you add automated tests with the @test thing? There are examples in the codebase. Also please add indentation where appropriate. Thanks!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Deeeeksha** [comment]
Thankyou @siriak . I will make changes as requested

**Comment by zhrgithub** [comment]
No problem


| |
张泓锐
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年01月18日 00:26，Deeksha ***@***.***> 写道：

Thankyou @siriak . I will make changes as requested

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhrgithub** [comment]
no thanks



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月18日 08:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TheAlgorithms/Java] CountFriendsPairing Algorithm Added (PR #2889) |

This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by siddhant2002** [comment]
@siriak please check the pr

**Review by siriak — CHANGES_REQUESTED** [review]
My latest review comments were not addressed. Proper indentation and automated tests need to be added

**Comment by siddhant2002** [comment]
@siriak I've added the test and indentation

**Comment by siriak** [comment]
image
I don't see your changes, have you done them in this branch?

**Comment by siddhant2002** [comment]
@siriak I've created my own file where I've added the code and test cases. Please do check @ https://github.com/siddhant2002/Java/blob/master/src/main/java/com/thealgorithms/dynamicprogramming/CountFriendsPairing.java and https://github.com/siddhant2002/Java/blob/master/src/test/java/com/thealgorithms/others/CountFriendsPairingTest.java

**Comment by siriak** [comment]
The code looks good, could you make a PR with your changes?

**Pull request closed without merging**
