### PR TITLE
Create Josephus.java

### PR DESCRIPTION
**Pull request by TRIPATHISHIWANSHI**
- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Review by vil02 — CHANGES_REQUESTED** [review]
As in #4421:

Please remove the `main` method and instead add some proper tests. Good examples to look at:
- [`Factorial`](https://github.com/TheAlgorithms/Java/blob/566c27a996f48a94916170c159ae735546b39c42/src/main/java/com/thealgorithms/maths/Factorial.java) and [`FactorialTest`](https://github.com/TheAlgorithms/Java/blob/566c27a996f48a94916170c159ae735546b39c42/src/test/java/com/thealgorithms/maths/FactorialTest.java),
- [`FindMax`](https://github.com/TheAlgorithms/Java/blob/566c27a996f48a94916170c159ae735546b39c42/src/main/java/com/thealgorithms/maths/FindMax.java) and [`FindMaxTest`](https://github.com/TheAlgorithms/Java/blob/566c27a996f48a94916170c159ae735546b39c42/src/test/java/com/thealgorithms/maths/FindMaxTest.java).

Please make sure to _check_ all of the _boxes_ in the PR (i.e. change `[ ]` to `[x]`).

If something is unclear: please ask.

By the way this PR is exactly the same as #4421 - please remove one of them.

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Comment by vil02** [comment]
@TRIPATHISHIWANSHI what is the progress? Do you need some help?

**Comment by TRIPATHISHIWANSHI** [comment]
yeah...I have done what you have said..but don't know...whether is it right
way or not??

**Comment by debasishbsws** [comment]
I am not sure but is it somehow different from the already available JosephusProblem in the math section
https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/maths/JosephusProblem.java

**Comment by vil02** [comment]
> I am not sure but is it somehow different from the already available JosephusProblem in the math section https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/maths/JosephusProblem.java

But the approach here uses different method (it is more _straightforward_). Since it is a good exercise in using queues I would leave it. One could write a test checking it both approaches give the same result.

In other words: @TRIPATHISHIWANSHI feel free to continue working on this.

**Pull request closed without merging**
