### PR TITLE
PR for adding new DP Problem Statement to calculateMaxNonAdjacentSum of 2D Array

### PR DESCRIPTION
**Pull request by swarnim0308**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java
- [x] Code is formatted by basic Intellij Idea Java format.

### CODE REVIEW

**Comment by swarnim0308** [comment]
I am not able to run clang-format -i --style=file path/to/your/file.java.  Getting below clang-format : The term 'clang-format' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ clang-format -i --style=file MaximumSumWithoutAdjacent.java
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (clang-format:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by swarnim0308** [comment]
clang format issue fixed. Put for review now.

**Comment by swarnim0308** [comment]
Can you please do the review

**Comment by siriak** [comment]
We do not add problems just from Leetcode/geeksforgeeks. If there are other sources for it like Wikipedia, please add a link to them

**Pull request closed without merging**
