### PR TITLE
Added Javadoc comments: I added Javadoc-style comments to provide doc…

### PR DESCRIPTION
**Pull request by sunilnitdgp**
…umentation for the class and the cutRod method. These comments explain the purpose of the class and method and provide details about their parameters and return values, improving code readability and understandability.  Clarified parameter names: I changed the parameter name from arr to price to make it clear that this array represents the prices of different pieces of the rod. This change improves the clarity of the code.  Improved variable names: I renamed max_val to maxVal to follow Java naming conventions, where variable names use camelCase. This makes the code more consistent and readable.  Added comments within the method: I added comments within the cutRod method to explain its logic. These comments clarify the purpose of the loops and the array val, making it easier for others to understand the code.

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by sunilnitdgp** [comment]
I request the maintainer(s) to merge my request using "hacktoberfest-accepted" label.

**Comment by sunilnitdgp** [comment]
@siriak Can you please review and merge this?

**Review by siriak — CHANGES_REQUESTED** [review]
The code looks good, could you please replace `main` with some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

**Comment by sunilnitdgp** [comment]
@siriak I've already raised a PR for the unit tests of this class, you can find the PR here: https://github.com/TheAlgorithms/Java/pull/4744

**Comment by sunilnitdgp** [comment]
@siriak Why this is being closed? https://github.com/TheAlgorithms/Java/pull/4744 is related to test cases and the current PR is regarding the code refactoring

**Comment by siriak** [comment]
My bad, I thought the changes from this PR are already included in #4744. Let's then wait for it to be merged, and then we will have a better understanding if the refactoring is correct

**Comment by siriak** [comment]
But ideally these 2 should be merged together in a single PR

**Comment by sunilnitdgp** [comment]
@siriak I've created 2 PRs because of the separation of concerns. This is related to the refactoring of the Rodcutting class where the core logic remains the same and other PR is related to test cases of the Rodcutting class.

**Review by debasishbsws — APPROVED** [review]
Thanks

**Review by siriak — APPROVED** [review]

**Pull request merged**
