### PR TITLE
added java code of babylonian method

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
### **Describe your change:**

- Add an algorithm

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
Please replace main() with tests as in https://github.com/TheAlgorithms/Java/blob/98656cb0cdacd175559272bcbb8bc3b86ddac52a/src/test/java/com/thealgorithms/maths/KaprekarNumbersTest.java, everything else looks good, thanks!

**Comment by SaumyaBhushan** [comment]
> 

replaced main() with test.

**Review by 22aam — APPROVED** [review]

**Comment by 22aam** [comment]
can you tell me about this pull request

**Comment by SaumyaBhushan** [comment]
> can you tell me about this pull request

Babylonian method is an iterative method to find the square root of a number. This is also sometimes called as Hero's method

**Review by siriak — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
