### PR TITLE
Added another Optimized solution for Anagrams check.

### PR DESCRIPTION
**Pull request by manojCode94**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

/*Respected Maintainer of this Repository, I hope this message finds you well. I am writing to propose another optimized solution for checking if two strings are anagrams or not in Java.
*/

**Approach**
```
boolean isAnagram(String s, String t) {
    if (s.length() != t.length()) {
        return false;
    }
    int[] freq = new int[26];
    for (int i = 0; i < s.length(); i++) {
      int pos1 = s.charAt(i) - 'a';
      int pos2 = s.charAt(i) - 'a';
      freq[pos1]++;  freq[pos2]--;
    }
    for (int i = 0; i < 26; i++) {
        if (freq[i] != 0) {
            return false;
        }
    }
    return true;
}
```

- If the lengths of the two strings are different, they cannot be anagrams. Return false.
- Initialize an array of size 26, where each element corresponds to the frequency of a character.
- Iterate through both strings, incrementing the frequency of each character in the first string and decrementing the frequency of each character in the second string.
- Iterate through the frequency array and check if all the elements are zero. If so, the two strings are anagrams of each other. Return true.
- If any element in the frequency array is non-zero, the two strings are not anagrams of each other. Return false.

**Complexity**

- The time complexity of this approach is O(n), where n is the length of the input strings.
- The space complexity is O(1), as we are using a fixed-size array. This approach is faster than using a hashmap, as it avoids the overhead of creating and iterating through a hashmap.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
The code looks good, could you please add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

**Comment by manojCode94** [comment]
Added JUnit Test as per suggested for Approach5 in AnagramsTest.java Build successfully.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by manojCode94** [comment]
Thanks @siriak

**Pull request merged**
