### PR TITLE
Adding a countFrequency.java

### PR DESCRIPTION
**Pull request by 123shuklaayush**
well, I checked your java programs and I think that this was missing so thought of contributing it :)

### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by 123shuklaayush** [comment]
an important code for the learners who would be learning HashMaps because counting the frequency is used many times in the programming

**Comment by 123shuklaayush** [comment]
Added countFrequency.java

**Review by AnuragKumar007 — CHANGES_REQUESTED** [review]
Bro, Where is the Class?
i.e. 
public class countfrequency{
}

**Comment by 123shuklaayush** [comment]
> Bro, Where is the Class? i.e. public class countfrequency{ }
Oh,  I didn't notice that

**Comment by siriak** [comment]
Not an algorithm

**Pull request closed without merging**
