### PR TITLE
add BigInteger implementation to Factorial.java

### PR DESCRIPTION
**Pull request by antailbaxt3r**
### **Describe your change:**

The previous implementation of Math/Factorial.java involved usage of ```long``` datatypes that have large storage, but it cannot even handle 100 factorial. So to solve this, I have implemented the algorithm using ```java.math.BigInteger``` which can store values upto 2^32-1 digits.

[BigInteger Oracle Documentation](https://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html)

* [ ] Add an algorithm?
* [X] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

#### References

Issue #1682 - Add BigInteger Implementation to Factorial.java

### **Checklist:**

* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Java files are placed inside an existing directory.
* [X] All filenames are in all uppercase characters with no spaces or dashes.
* [X] All functions and variable names follow Java naming conventions.

### CODE REVIEW

**Review by ShivamShekhar1997 — APPROVED** [review]
**The BigInteger implementation seems to be a proper one**

**Comment by sanjana1604** [comment]
@ShivamShekhar1997 Is the issue is still open and if yes can you tell me what needs to be done?

**Comment by ShivamShekhar1997** [comment]
> @ShivamShekhar1997 Is the issue is still open and if yes can you tell me what needs to be done?

No @sanjana1604  I guess the implementation is a good one and I don't see the need of any changes, just needs to be merged, thanks anyways!

**Comment by antailbaxt3r** [comment]
If the PR is valid please get it merged, thank you!

**Pull request closed without merging**
