### PR TITLE
Rotate a LinkedList #4332

### PR DESCRIPTION
**Pull request by csengineer1990**
I have implemented the Rotate LinkedList which fixes issue #4332 .

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by csengineer1990** [comment]
Hi, I am first time contributing here. So please let me know if I did anything wrong and also tell me if there are any changes required.?

**Comment by debasishbsws** [comment]
it is already present in SinglyLinkedList https://github.com/TheAlgorithms/Java/blob/f010a47608607a2622a49a4414e7fbf4b4a7ee03/src/main/java/com/thealgorithms/datastructures/lists/SinglyLinkedList.java#L127-L162

But you can try to create another class for a generic linkedlist reversal method. And try to reuse the already present classes, and instead of main method adding junit test is preferable..

**Comment by csengineer1990** [comment]
> it is already present in SinglyLinkedList
> 
> https://github.com/TheAlgorithms/Java/blob/f010a47608607a2622a49a4414e7fbf4b4a7ee03/src/main/java/com/thealgorithms/datastructures/lists/SinglyLinkedList.java#L127-L162
> 
> But you can try to create another class for a generic linkedlist reversal method. And try to reuse the already present classes, and instead of main method adding junit test is preferable..



sorry sir but I got confused. I have given Rotate LinkedList algo with example. Now you are saying in the SinglyLinkedList Algo reverse linkedlist code is present. I didn't get that. now what should I have to do? please correct me if I asked wrong or I didn't understand what did you said.

**Comment by siriak** [comment]
This algorithm is already implemented, so the PR can be closed

**Pull request closed without merging**
