### PR TITLE
Partition Problem using Dynamic Programming

### PR DESCRIPTION
**Pull request by asifjoardar**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
It's already present here https://github.com/TheAlgorithms/Java/blob/3a593d5d3c5dc7099ec5e5a6d26f5fc9fd59b34a/src/main/java/com/thealgorithms/dynamicprogramming/SubsetSum.java#L3, please reuse the existing implementation and add JUnit tests

**Comment by siriak** [comment]
Sure

**Comment by asifjoardar** [comment]
@siriak can you please review it again?

**Review by siriak — CHANGES_REQUESTED** [review]

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
