### PR TITLE
WildcardMatching Added

### PR DESCRIPTION
**Pull request by janmeshjs**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
The code looks good, could you please add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

**Comment by janmeshjs** [comment]
Added JUnit tests for the review.

**Comment by janmeshjs** [comment]
I tried reformatting but the error with clang format still persist.

**Comment by BamaCharanChhandogi** [comment]
Try to solve the clang issue. 
The `-` sign means you have to remove that line from your code. and `+` sign means you have to add that line.

**Comment by janmeshjs** [comment]
All issues resolved. Thank you.
@siriak @BamaCharanChhandogi

**Review by siriak — CHANGES_REQUESTED** [review]
Please remove `main`, it's redundant

**Comment by janmeshjs** [comment]
> Please remove `main`, it's redundant

Done! Please let me know if any other changes are required.

**Review by BamaCharanChhandogi — APPROVED** [review]
looks good thanks

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
