### PR TITLE
feat: Increase coverage for MaximumMinimumWindow.calculateMaxOfMin() …

### PR DESCRIPTION
**Pull request by chubretovic**
3 test are running good and one is bad (checkBasicCase()). However, now the percentage of branches taken is 100%.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
The tests look good, but could you exclude the code coverage and changes related to it?

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Comment by siriak** [comment]
@siddhant2002 sure

**Pull request closed without merging**
