### PR TITLE
Added MapReduce Algorithm in Misc Folder.

### PR DESCRIPTION
**Pull request by aakiliqbal**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
**Hello @aakiliqbal,**
You have to create another function for this operation. Next, remove the main method and then add test cases.
You can understand this:
[https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/backtracking/ArrayCombination.java](url)
[https://github.com/TheAlgorithms/Java/blob/master/src/test/java/com/thealgorithms/backtracking/ArrayCombinationTest.java](url)

**Review by BamaCharanChhandogi — COMMENTED** [review]
**Hello @aakiliqbal,**
You have to create another function for this operation. Next, remove the main method and then add test cases.
You can understand this:
[https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/backtracking/ArrayCombination.java](url)
[https://github.com/TheAlgorithms/Java/blob/master/src/test/java/com/thealgorithms/backtracking/ArrayCombinationTest.java](url)

**Comment by aakiliqbal** [comment]
> **Hello @aakiliqbal,** You have to create another function for this operation. Next, remove the main method and then add test cases. You can understand this: [https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/backtracking/ArrayCombination.java](url) [https://github.com/TheAlgorithms/Java/blob/master/src/test/java/com/thealgorithms/backtracking/ArrayCombinationTest.java](url)

Hey @BamaCharanChhandogi Thanks for the reply, Ok Sure.

**Comment by aakiliqbal** [comment]
Hey, @BamaCharanChhandogi Can you review my code? I have removed the main method and put my main code in MapReduce function along with some test cases in MapReduceTest.

**Review by BamaCharanChhandogi — APPROVED** [review]
looks good, thanks.

**Comment by aakiliqbal** [comment]
Thanks @BamaCharanChhandogi.

**Pull request merged**
