### PR TITLE
Implement Sher Lock and Cost Problem.

### PR DESCRIPTION
**Pull request by GouthamGuna**
- [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [X] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [X] All functions and variable names follow Java naming conventions.
- [X] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [X] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by GouthamGuna** [comment]
What are the problems with the code?

**Comment by BamaCharanChhandogi** [comment]
Hi @GouthamGuna,
Firstly fix formatting issues. 
If you expand the build you can see `-` and `+` signed. 
It means you have to remove the `-` line code and add the `+` line code.

**Review by BamaCharanChhandogi — COMMENTED** [review]
Hi @GouthamGuna ,
Firstly fix formatting issues. 
If you expand the build you can see `-` and `+` signed. 
It means you have to remove the `-` line code and add the `+` line code.

**Comment by GouthamGuna** [comment]
Hi @yanglbme, @vil02 

Please review the code, and if it meets your approval, proceed to approve it. Otherwise, I would appreciate suggestions for improvement.

**Comment by vil02** [comment]
@GouthamGuna the problem looks like a _leetcode_ puzzle and:
https://github.com/TheAlgorithms/Java/blob/2568b96784e50ce517aa223e29302fc10ef3caac/CONTRIBUTING.md?plain=1#L3

In my opinion this simply does not fit to this repository.

@BamaCharanChhandogi what is your opinion?

**Pull request closed without merging**
