### PR TITLE
Test Codes and Refactoring of SinglyLinkedList

### PR DESCRIPTION
**Pull request by ales-blaze**
I am a little bit worried about the test cases!
So waiting for your suggestions for that.

### CODE REVIEW

**Comment by varunu28** [comment]
@ales-blaze Thanks. Would look into it later during the day

**Comment by varunu28** [comment]
@ales-blaze We are adding tests to Development branch. Therefore you have to open a PR against Development. I am closing this PR. You can raise another PR

**Comment by ales-blaze** [comment]
Ok @varunu28, but what is your opinion about the test?
Are they good or bad ?

**Comment by varunu28** [comment]
@ales-blaze  You would have to follow a proper naming convention. Please have a look at this [thread](https://stackoverflow.com/questions/155436/unit-test-naming-best-practices)

Also, the tests should be pretty generic. A test ```headMustNullAfterDeletion``` is not generic because the head would not be null after every deletion if the list contains more than 1 nodes. 

Go ahead and raise the PR and I would review it thoroughly.

**Pull request closed without merging**
