### PR TITLE
AES cipher in CBC version 1 mode

### LINKED ISSUE #4586: [FEATURE REQUEST] AES cipher in CBC v1 mode
### What would you like to Propose?

New Algorithm under
https://github.com/TheAlgorithms/Java/tree/master/src/main/java/com/thealgorithms/ciphers

File Name Proposed: AES_CBC_v1.java

What?
An implementation of CBC version 1 mode of AES algorithm in java.

### Issue details

The AES algorithm operates in multiple modes, CBC (Cypher Block-Chaining) is one of the most popular and well-known modes. An implementation of CBC v1 mode of AES algorithm would be really good in this repository. 

Note: This issue is self-assigned and PR is raised as a part of Hacktoberfest

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ojasva**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

"Fixes #4586"

### CODE REVIEW

**Comment by 0x3C50** [comment]
The IV in this implementation seemingly does nothing, decrypting data seems to use a random IV instead of the actual IV used when encrypting. Have you tested this properly?

Also, is this thread safe?

**Comment by ojasva** [comment]
> > The IV in this implementation seemingly does nothing, decrypting data seems to use a random IV instead of the actual IV used when encrypting. Have you tested this properly?
> > Also, is this thread safe?

* Hey, I am sorry I closed the PR by mistake.

To quote the implementation of IV, the IV is not necessarily secret in AES-CBC. Hence, is appended with the cipher text itself. Therefore, it is not needed for decryption, which is handled by mode in the above code. 
I hope i answered to your query as needed. :)

**Comment by 0x3C50** [comment]
> > > The IV in this implementation seemingly does nothing, decrypting data seems to use a random IV instead of the actual IV used when encrypting. Have you tested this properly?
> 
> > > Also, is this thread safe?
> 
> 
> 
> * Hey, I am sorry I closed the PR by mistake.
> 
> 
> 
> To quote the implementation of IV, the IV is not necessarily secret in AES-CBC. Hence, is appended with the cipher text itself. Therefore, it is not needed for decryption, which is handled by mode in the above code. 
> 
> I hope i answered to your query as needed. :)

The IV is integral for decrypting data in some modes. In your use case tho, it is not being passed to the Cipher at all, and acts more like a salt, being appended to the data being encrypted and thrown away once decrypted.

**Comment by ojasva** [comment]
> > > > The IV in this implementation seemingly does nothing, decrypting data seems to use a random IV instead of the actual IV used when encrypting. Have you tested this properly?
> > 
> > 
> > > > Also, is this thread safe?
> > 
> > 
> > 
> > * Hey, I am sorry I closed the PR by mistake.
> > 
> > To quote the implementation of IV, the IV is not necessarily secret in AES-CBC. Hence, is appended with the cipher text itself. Therefore, it is not needed for decryption, which is handled by mode in the above code.
> > I hope i answered to your query as needed. :)
> 
> The IV is integral for decrypting data in some modes. In your use case tho, it is not being passed to the Cipher at all, and acts more like a salt, being appended to the data being encrypted and thrown away once decrypted.

That's pretty much true honestly. To my knowledge in CBC version 1, the IV was not utilized properly and hence were the further versions developed. I also plan to drop the enhanced version of the algorithm to this repository in future. I hope it'll help.

**Pull request closed without merging**
