### PR TITLE
Code for LowestSetBitManipulation added

### PR DESCRIPTION
**Pull request by ishanki19-pixel**
# Pull Request: Added `LowestSetBit` Class for Efficient Bit Manipulation( Fix: #5567)

## Description
This pull request introduces the `LowestSetBit` class, which provides efficient methods for isolating and clearing the lowest set bit of an integer using bitwise operations.

### Key Features
- **`isolateLowestSetBit(int n)`**: Returns the value of the lowest set bit in the given integer.
- **`clearLowestSetBit(int n)`**: Returns the integer with its lowest set bit cleared.

### Edge Case Handling
- Handles the case when `n = 0` by returning `0` (no set bits).
- Works correctly with both positive and negative integers.

### Performance Analysis
- **Time Complexity**: Both methods operate in constant time `O(1)` due to direct bitwise operations.
- **Space Complexity**: The space complexity is `O(1)`, as no additional space is used beyond the input variable.

---

## Checklist

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`.

### CODE REVIEW

**Comment by prayas7102** [comment]
@ishanki19-pixel The PR for which you're providing a fix already had clearLowestSetBit(int n) from it's initial commits, and it already handles corner cases like 0s and negative numbers.

**Comment by ishanki19-pixel** [comment]
> @ishanki19-pixel The PR for which you're providing a fix already had clearLowestSetBit(int n) from it's initial commits, and it already handles corner cases like 0s and negative numbers.

Yeah, I was bit confused with testing stuff, I am resolving this in a while.

**Comment by ishanki19-pixel** [comment]
@prayas7102 Please review this once again!

**Comment by prayas7102** [comment]
> @prayas7102 Please review this once again!



> @ishanki19-pixel The PR for which you're providing a fix already had clearLowestSetBit(int n) from it's initial commits, and it already handles corner cases like 0s and negative numbers.

Hey @ishanki19-pixel I'm not the reviewer for this repository; I'm also a contributor. What I was asking is, all the changes you've made in this PR are already present in PR #5574. So, what is the purpose of this PR?

**Comment by ishanki19-pixel** [comment]
> > @prayas7102 Please review this once again!
> 
> > @ishanki19-pixel The PR for which you're providing a fix already had clearLowestSetBit(int n) from it's initial commits, and it already handles corner cases like 0s and negative numbers.
> 
> Hey @ishanki19-pixel I'm not the reviewer for this repository; I'm also a contributor. What I was asking is, all the changes you've made in this PR are already present in PR #5574. So, what is the purpose of this PR?

But this pr is itself #5574 , its id is itself 5574. I am not able to understand what are you trying to saying because you are referring the same PR in which you are commenting now

**Comment by prayas7102** [comment]
> > > @prayas7102 Please review this once again!
> > 
> > 
> > > @ishanki19-pixel The PR for which you're providing a fix already had clearLowestSetBit(int n) from it's initial commits, and it already handles corner cases like 0s and negative numbers.
> > 
> > 
> > Hey @ishanki19-pixel I'm not the reviewer for this repository; I'm also a contributor. What I was asking is, all the changes you've made in this PR are already present in PR #5574. So, what is the purpose of this PR?
> 
> But this pr is itself #5574 , its id is itself 5574. I am not able to understand what are you trying to saying because you are referring the same PR in which you are commenting now

Sorry for the confusion, it's #5567 which i was trying to refer.

**Review by siriak — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Pull request closed without merging**
