### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Abinashbunty**
Modified the content by removing redundant info and styled it.

### **Describe your change:**

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [x] Documentation change?

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Abinashbunty** [comment]
I had to reopen it because it shows "build Expected - Waiting for status to be reported". And the online references suggested to close and reopen. 
This still doesn't work. Can you let me know where it might be going wrong? Thanks! 😄

**Comment by Abinashbunty** [comment]
It is a documentation change. Perhaps that is why no "build" is required.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by siriak** [comment]
`build` GitHub action had some conditions that prevented it from running in your PR. This is fixed now.

**Review by debasishbsws — APPROVED** [review]
Looks good 👍

**Comment by Abinashbunty** [comment]
Thanks guys. 👍🏻😊

**Pull request merged**
