### PR TITLE
Added Dijkstra Graph Algorithm

### PR DESCRIPTION
**Pull request by Anshul-9923**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by Anshul-9923** [comment]
@BurkHufnagel @arindam89 @qckzr I have added code for Dijkstra Algorithm. Please merge the PR.

**Comment by arindam89** [comment]
Can you rebase with the base branch it seems out of date

**Comment by Anshul-9923** [comment]
@arindam89 Done

**Comment by Anshul-9923** [comment]
@arindam89 Is this fine or do I need to make any other change?

**Comment by Anshul-9923** [comment]
@siriak Please review my PR.

**Comment by siriak** [comment]
This algorithm is already present here https://github.com/TheAlgorithms/Java/blob/a1638165fead8abf2cab44f6ef58ba5592c4bead/src/main/java/com/thealgorithms/datastructures/graphs/DijkstraAlgorithm.java#L8

**Pull request closed without merging**
