### PR TITLE
Update HashMap.java

### PR DESCRIPTION
**Pull request by sunilnitdgp**
Changes

SOLID Principles:

Single Responsibility Principle: Each class (HashMap, LinkedList, Entry) has a clear single responsibility. For example, the HashMap class manages the hash map, LinkedList handles linked list operations, and Entry represents a key-value pair. Open-Closed Principle: The code is designed to be open for extension (e.g., adding new methods) but closed for modification (existing methods are not changed). Reliable:

Improved code readability and maintainability by following SOLID principles and Java conventions. Added bounds checking to handle potential IndexOutOfBoundsException. Extensible:

The code is extensible, allowing for future additions of methods or features without modifying existing code. This is achieved by adhering to the Open-Closed Principle. Javadoc Comments:

Added Javadoc comments to provide comprehensive documentation for each class and method, enhancing code understanding and usability.

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [ ] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by sunilnitdgp** [comment]
I request the maintainer(s) to merge my request using "hacktoberfest-accepted" label.

**Comment by Jyotishmoy12** [comment]
can you plss help me how to resolve that issue related to clang-format??

**Comment by sunilnitdgp** [comment]
Hi @Jyotishmoy12 You can check the Clang format linter build logs and you can see some + and -, and if your build failed. That means you need to remove those '-' lines and add '+' lines with mentioned formatting.

**Comment by Jyotishmoy12** [comment]
Thanks a lot for your help!

**Pull request closed without merging**
