### PR TITLE
Add Diagonal 2x2 Matrix Algorithm

### PR DESCRIPTION
**Pull request by msoud25**
Feature Request - add Diagonal Matrix Algorithm to maths folder 
- [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x ] This pull request is all my own work -- I have not plagiarized it.
- [ x] All filenames are in PascalCase.
- [ x] All functions and variable names follow Java naming conventions.
- [ x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [ x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Comment by vil02** [comment]
I am not sure if this _algorithm_ is not too simple - could you generalize it for any square matrix? @siriak, @BamaCharanChhandogi - what is your opinion?

In any case: before this can be merged, the first thing to do is to add proper junit tests.

**Comment by BamaCharanChhandogi** [comment]
Yes, first of all, add test cases. Then it will be clearer.

**Comment by siriak** [comment]
I agree that it should be generic for any `nxn` matrix (if applicable)

**Review by BamaCharanChhandogi — COMMENTED** [review]
@msoud25 what about updates?

**Pull request closed without merging**
