### PR TITLE
Create LongDivision.java

### PR DESCRIPTION
**Pull request by adjamalbek**
It's not a simple division, it's a division which is implemented using Long Division Principle, which saves us a lot of time, where some users approach using while loop.

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by debasishbsws** [comment]
Add Some JUnit test

**Comment by adjamalbek** [comment]
> 
I did: 
https://github.com/TheAlgorithms/Java/pull/3710

**Comment by adjamalbek** [comment]
Test and Main are combined, all the errors were fixed, please kindly review, thank you

**Comment by adjamalbek** [comment]
Requesting review from @siriak and @yanglbme and @debasishbsws for approval and merging.

**Review by siriak — CHANGES_REQUESTED** [review]
Is this a well-known computer science problem and algorithm? Please add some links to problem statement and algorithm explanation

**Comment by siriak** [comment]
Then please call it LongDivision and add a link to Wikipedia

**Comment by adjamalbek** [comment]
I have a left a source and short description in the Main Java class and added a comment, also the name of the Class was changed

**Review by debasishbsws — COMMENTED** [review]
@siriak  Long division is an algorithm to divide long numbers, in small step-by-step from. It doesn't make any sense if the inputs are bounded to only integers. input and output should be in a string so that very big size numbers can be divided using this.

**Comment by adjamalbek** [comment]
This my 1st attempt by using integers only, I can write a code in a future and update the current method, which will accept numbers as strings, cause initially it was and integer division by long division method

**Review by debasishbsws — APPROVED** [review]

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
