### PR TITLE
update pss.java

### PR DESCRIPTION
**Pull request by khwaishchawla**
Proportional Share Scheduling (PSS) is a scheduling algorithm that assigns each process a weight based on its priority, and processes are scheduled to receive CPU time in proportion to their assigned weights. The higher the weight of a process, the more CPU time it will receive compared to processes with lower weights.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
The code looks good, could you please remove main and add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

**Review by khwaishchawla — COMMENTED** [review]
made the required changes as asked

**Comment by khwaishchawla** [comment]
> The code looks good, could you please remove main and add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

Done with all the reqirements kindy review it

**Comment by siriak** [comment]
There are no JUnit tests and PR checks are failing
image

**Pull request closed without merging**
