### PR TITLE
Added Doubly Linked List

### PR DESCRIPTION
**Pull request by rnitish**
Added doubly linked list data structure

Overview:
- Insertion at start
- deletion from start
- deletion of a specified element
- get size of list

### CODE REVIEW

**Comment by rbshealy** [comment]
There is already a doubly linked list data structure if I am not mistaken

**Comment by rnitish** [comment]
Actually this one is a generic doubly linked list.

Also pull request is for development branch where there is no doubly linked list.

**Review by mTab86 — CHANGES_REQUESTED** [review]
I think the delete method in doubly linked list will give null pointer exception.

**Comment by rnitish** [comment]
Thanks @mTab86 

I will fix the same.

**Comment by ayaankhan98** [comment]
Hey please make PR to master branch.

**Pull request closed without merging**
