### PR TITLE
Create ModularExponentiation.java

### PR DESCRIPTION
**Pull request by lulunac27a**
Add modular exponentiation in Java

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a [URL](https://www.geeksforgeeks.org/modular-exponentiation-power-in-modular-arithmetic/) in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

**Review by vil02 — CHANGES_REQUESTED** [review]
Please:
- add proper junit tests,
- your code does not work for negative `y`,
- reformat the code,
- please apply your function in other places, where this function is needed, e.g.
  - https://github.com/TheAlgorithms/Java/blob/da21ffe78c79d6b4e4d420f4ce862a1bedd2024e/src/main/java/com/thealgorithms/maths/PrimeCheck.java#L74,
  - https://github.com/TheAlgorithms/Java/blob/da21ffe78c79d6b4e4d420f4ce862a1bedd2024e/src/main/java/com/thealgorithms/maths/MillerRabinPrimalityCheck.java#L75.

I also think that this could be a _generic_, to handle `int`s and `long`s.

Further more, what do you think about renaming it to `modPow` - this seems to be a more standard name in this context.

**Comment by lulunac27a** [comment]
Add tests and code if y (power) is 0, return 1

**Comment by vil02** [comment]
I think you also want to throw an exception for `y < 0`.

**Comment by vil02** [comment]
@lulunac27a please fix all of the errors from the CI and please have a look at my [previous comment](https://github.com/TheAlgorithms/Java/pull/5091#pullrequestreview-1969918047).

**Comment by lulunac27a** [comment]
Fixed errors by formatting code and changing function name to `modPow`

**Pull request closed without merging**
