### PR TITLE
Geo

### PR DESCRIPTION
**Pull request by Salik147**
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by Salik147** [comment]
Don't know why I am getting this error on Doozyx/clang-format-lint-action@v0.16.2 however the code works fine please help me to resolve this problem so that this contribution could be merge in this repository

**Comment by amul67142** [comment]
Its a formatting issue. Use a formatter which fix spacing

**Comment by Salik147** [comment]
> Its a formatting issue. Use a formatter which fix spacing

Thanks a lot for the assistance.

**Comment by BamaCharanChhandogi** [comment]
Remove the main method. and add test cases.

**Comment by Salik147** [comment]
I have added test cases and removed the main method but it is showing me an error on just one curly braces  which I don't know why however I have installed linter extension on my VScode but it is not working or may be outdated

**Comment by Salik147** [comment]
> Remove the main method. and add test cases.
I have added test cases and removed the main method but it is showing me an error on just one curly braces which I don't know why however I have installed linter extension on my VScode but it is not working or may be outdated, it would be great if you could suggest some extensions or way to solve it or simply ignore that please tell me if there is anything I could fix in order to merge it

**Pull request closed without merging**
