### PR TITLE
#4459 - Added code to find Articulation Points and Bridges

### PR DESCRIPTION
**Pull request by Prabhat-Kumar-42**
Description : 
New Feature - Added Articulation Point and Bridge Algo.
Helps to find the articulation points and bridges in graph.
Detailed Explanation is added in code.

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by Prabhat-Kumar-42** [comment]
Hey, I loved the idea of an algorithm library.
I added code for articulation points and bridges for graphs.

This is my first open-source contribution. Hope It will help the community.

I don't know about lint checks, and how to fix it. If it's of any issue, please inform me, I would love to know how to fix it and will do it.

Thank You !!

**Comment by Prabhat-Kumar-42** [comment]
Fixed Lint

**Review by Ameerjafar — APPROVED** [review]

**Comment by Prabhat-Kumar-42** [comment]
I request the maintainer(s) to please merge my request using "hacktoberfest-accepted" label.
Thank You !!

**Comment by Prabhat-Kumar-42** [comment]
**Pull Request Review Request**

Hey,

Please review the PR. I have added the source code along with a test-case file.

If you identify any issues with the code, please do let me know. I will fix them asap.

Otherwise, if everything looks good, I would appreciate your approval to merge the code.

Thank you !!

**Comment by vil02** [comment]
@Prabhat-Kumar-42 please apply all of the _meta suggestions_ from #4465 here.

**Comment by Prabhat-Kumar-42** [comment]
@vil02 , yes, I will surely.

**Pull request closed without merging**
